= R7RS index
:toc: left

R7RS index is a tool for indexing and searching through procedures and syntax from R7RS-small and R7RS-large libraries.
R7RS index can be used in 3 ways - as a site (https://r7rsindex.com), through REST API, or through stdio API

== Userguide for site visitors

R7RS index search consists of control pane on the left, and result list in the center. 

=== Control pane

In the control pane, optionally select values from the filter list, optionally enter search query in the text field, and press either enter or button with magnifying glass to display the results. If you have javascript enabled, typing in the search query field should give you auto suggestions for identifier names, although those suggestions are not filtered by current selection. If you have javascript enabled and have checked apropriate option in settings, you can use control + f to quickly focus to the query text field.

=== Result list

Each result item can be either a procedure, a macro, or a value. At the top it shows a library it is exported from. Note, that some identifiers are exported from multiple libraries. The library name can be pressed, which will result in starting new search using said library as a filter. On the right side top, associated list of tags with the result is shown. Like with library, tags are also clickable, and start a search using the clicked tag as a filter.

Procedure, procedure-like macros and value names are rendered in *red*. Procedures are distinguished by being surrounded with parenthesis, as if being called. Following the name until the "=>" sign are parameters. If parameter is just a name, it means it has an unspecified type. Otherwise, parameter may be a list of type and name. Types are represented as predicate procedures. After the "=>" sign is the return type. The return can be one of: 

* predicate procedure name (just like parameter type); 

* a "*" symbol (meaning it returns a value of unknown type); 

* a word "undefined" (meaning it returns a value which shouldn't be used in portable code); 

* a list with "values" word in car position (meaning it has a multivalue return); 

* a list with "or" word in car position (meaning the return type is a union between given types). 

Types expressed as predicates in *blue* are links. Pressing on a type in parameter position will search using that type as *return value* filter; pressing on a type in return value position will search using that type as *parameter* filter.

Scheme is a functional language and thus it'd be useful to specify taken / returned procedure values. Therefore, if one of parameters is *procedure?*, it's signature is defined below the main procedure's signature, using parameter's name in car position. Likewise same is done if return value is a procedure; but in that case word "return" is used as a name.

Procedures can have more than one entry, even from same library. This occurs, if the procedures is has optional parameters and therefore can be called in multiple ways; or if the result type can be determined more precisely under more specific input parameters.

Macros are rendered in *green*. If macro is complex, some parts of it are grouped, and the syntax of those groups shown below the syntax of whole macro. Macro literals are also rendered in green. To make parenthesis more obvious, auxiliary parenthesis coloring is used, however this coloring doesn't signify any information.

=== Tags

Result items might have one or more of following tags

* pure - this procedure is referentially transparent (as long as whatever procedure parameters it has are also referentially transparent). Procedures that return undefined value cannot be marked as pure;
* predicate - this procedure that takes any object and returns a boolean. Such procedure may be used as a type;
* parameterized - the behavior of the procedure depends on a dynamic parameter (ie, uses procedure created with "make-parameter");
* parameter - this procedure was created with "make-parameter" and may be used in parameterize form;
* deprecated - not recommended to be used, exists only for backwards compatibility with older SRFIs.

=== Filtering logic

Selecting multiple libraries, will return results that are part of *any* of the given libraries.

Selecting multiple tags, will return results that contain *all* of the given tags.

Selecting multiple parameter types will return results that match *all* of the given types. 

Some types contain logical "parent" / more general types, eg. *number?* is a parent of *integer?*. When searching by parameter type, the procedures that take parent type will be matched. However, the results with more precise "child" type are weight more heavily and should appear at the start of the search.

Some types are defined as a union of other types; for example *list?* is a union of *pair?* and *null?*. If loose parameter filtering is enabled under settings, the composing parts will be treated as parent of union type; ie searching for *list?* you'd be also presented with procedures applicable to *pair?*. On one hand this presents extra results you might be interested, on the other hand those results might not be applicable in general case.

Selecting multiple return types will return results that match *all* of the given types. As and in case filter by parameter type, when filtering by return type the type hierarchy is taken into consideration. Searching by a "parent" return type will also yield procedures returning more precise "child" types.

The text query is parsed by edismax parser, and is used to filter by name and parameter / subsyntax names. This means it supports and interprets common searching syntax, such as using "-" in front of the word to exclude results containing said word. This has its disadvantages; eg. if you tried to search for coercion functions and typed "->string" (without quotes) into the search input field, you wouldn't find anything interesting, because the leading minus was interpreted specially. Instead, you'd have to search using "exact phrase", by putting double quotes around the search.


== Building and running

=== Natively

You can build R7RS index by running `ant` from the root of the source directory. Note that the build process required following executables to be on path

* `ant` - Apache Ant build tool

* `mvn` - Apache maven project tool

* `asciidoctor` - Asciidoctor documentation compiler

After the build successfully completes, you should find everything R7RS index needs in `dist` directory.

Alternatively, you may find release zip available for downloads at https://github.com/arvyy/r7rs-index-site/releases.

Once you have the built version, you can run it using:

```
java -jar r7rs-index.jar
```

See <<Configuration>> section for configuring the application behavior.

=== Using docker

If you prefer using docker, you can build a docker image using

```
docker build -t r7rs-index -f docker/Dockerfile .
```

which can the be run with 

```
docker run -p 8080:8080 --init r7rs-index
```

The built image has same structure as a native build inside the `/app` path.

=== Running for development

First, install dependencies under kawa-web-collection submodule

```
cd kawa-web-collection
mvn install
```

Afterwards, run the application with

```
mvn kawa:run
```

== Configuration

=== Config.scm

Core application behavior is managed using a scm configuration file, containing a list of key-value pairs, where each key is a symbol (ie. an alist).
Running the application, first argument is interpreted as a path to configuration file. If not set, it defaults to `./config/configuration.scm`

The following is exhaustive list of valid properties
[cols="1l,3,1l"]
|===
| Property
| Description
| Default

| solr-embed
| Specify whether embed solr / lucene index inside the application itself (if `#t`), or connect to a standalone solr instance (if `#f`)
| #t

| solr-home
| Directory contain solr home / configuration. Relevant only if solr-embed is #t
| "./solrhome"

| solr-url
| Solr url to connect to. Relevant only if solr-embed is `#f`
| "http://localhost:8983/solr"

| solr-core
| Solr core to use
| "scmindex"

| enable-web
| Whether enable web ui and REST api
| #t

| port
| Which port to use. Relevant only if enable-web is `#t`
| 8080

| cache-templates
| Whether templates should be cached (ie compiled once and remembered). Use `#f` in development, so that you don't need to restart the app to see changes
| #t

| serve-static
| Whether application should serve static resources from ./static folder. Use `#f` if you have some other web server (eg nginx in front) serving the content.
| #t

| enable-repl
| Whether to enable stdio repl api
| #f

| spec-index
| Index of definitions to load (see Types definitions section)
| "./types/index.scm"
|===

=== Types definitions

Type definitions are structured into type files one for each library, and a single root index file which defines names and paths to those library files.
The index file is specified in configuration under `spec-index` property, with a default value "./types/index.scm".

Index should be a list of pairs - where `car` is a symbolic library name, and `cdr` is the file to load its definitions from.

```
(
    ((scheme base) . "types/scheme.base.scm")
)
```

Each library file is a list of entries, where each entry is an association list, using symbols as keys. An entry may be defining a function, a syntax macro, or a plain value.

[cols="1m,3a"]
|===
| key 
| description

| name
| The name of the function / syntax / value. The name doesn't have to be unique - in particular with procedures, definition is repeated for all possible invocation overloads with different parameter counts. Required.

| signature
| S-expr defining signature. The format depends on a type (function / syntax / value) being described.

== Function

In case of function, the format is `(lambda (<parameter> ...) <return type>)`

Each parameter is either of the form `(<type> param-name)` or just `param-name`, when type is "any". Each parameter may be succeeded by a `...` literal to indicate varargs / repetition.

Parameter type is either:

* a predicate name (eg. `list?`);

* a type union in the form of `(or <type> ...)` (eg. `(or list? number?)`). When using `or`, `#f` might be used as a type inside of it due to its common appearance as a "null" value.

Return type can be same as parameter type described above, plus:

* `undefined`, indicating a value that shouldn't be used in portable code (eg. result of `for-each`);

* `*`, indicating a useful value but of unknown type.

* `(values <type> ...)` form when the function returns more than one value.

== Syntax

In case of syntax, the format is `(syntax-rules (<keyword> ...) (<pattern> <optional-return-type>) ...)`

Pattern should be: symbol, `.`, `...`, or grouping of patterns inside `()`. If optional return type is provided, it describes
the resultant type when syntax is used as an expression. As a hatch to rendering outside of parens, use `(_append )` form, which concatenates its arguments.

== Value

In case of simple value, the format is `(value <type>)`

where type is same as described under functions.

| tags
| A list of symbols. Tags don't have inherent special treatment (ie., definition can make use of any tag it wants). 
Currently used tags are described in <<Tags>>

| subsigs
| Signatures of parameter / return functions in case of a higher order function; or syntax definition of pattern variables in case of syntax

== Function

Each entry in this list is a list, where first element is a parameter name (must match one of parameters in main signature), and second parameter
is its signature of same format as a main function's signature definition. To describe return value's signature, use `return` as a name.

== Syntax

Each entry in this list is a list, in the form of `(name <pattern> ...)`, where name should match one of identifiers
in other signature, and the pattern is as described in `signature`.

| syntax-param-signatures
| Applicable only to syntax type. The value is a list, where each element is itself a 2 element list. First element is a symbol, matching one of the symbols in the signature.
Second argument is parameter type definition, as described under functions. This allows annotating syntax when it expects to receive values of certain types for specific places in the pattern. 
|===


=== Logging

R7RS index uses logback for logging. By default (as defined in `src/main/resources/logback.xml`) it only does rolling file logging into `./logs` directory, and not into standard output.
You can provide custom logging configuration by running

```
java -Dlogback.configurationFile=/path/to/config.xml -jar r7rs-index.jar
```

Consult logback documentation for details.

== REST API

All of the following endpoints accept `wt` query parameter.
If the parameter's value is `sexpr`, the results are returned as if with `write`, using scheme-json convention
as defined in srfi 180. Otherwise, results are returned as json.

'''

=== `/rest/libs`

Libraries found in index as strings.

JSON schema
[source,json]
----
{
    "type": "array",
    "items": {
        "type": "string"
    }
}
----

Example response
[source,json]
----
["(scheme base)", "(scheme file)"]
----

'''

=== `/rest/tags` 

Tags found in index as strings.

JSON schema
[source,json]
----
{
    "type": "array",
    "items": {
        "type": "string"
    }
}
----

Example response
[source,json]
----
["pure", "deprecated"]
----

'''

=== `/rest/returns`

Types, which were used as a return type, found in index as strings.

JSON schema
[source,json]
----
{
    "type": "array",
    "items": {
        "type": "string"
    }
}
----

Example response
[source,json]
----
["list?", "pair?"]
----

'''

=== `/rest/params`

Types, which were used as a parameter type, found in index as strings.

JSON schema
[source,json]
----
{
    "type": "array",
    "items": {
        "type": "string"
    }
}
----

Example response
[source,json]
----
["list?", "pair?"]
----

'''

=== `/rest/search` 

Returns found identifiers and faceting meta data.

Query parameters

[cols="1l,3"]
|===
| query
| text search parameter. Query is parsed using edismax, and therefore some text tokens have special meaning

| start
| result offset (pagination).

| rows
| size of returned result list. Defaults to 40 if unspecified. 

| lib
| library filter. Possible values returned in `/rest/libs`. The parameter can appear multiple times, and the result will include procedures from any of given libraries.

| tag
| tag filter. Possible values returned in `/rest/tags`. The parameter can appear multiple times, and the result will include procedures which contain all given tags.

| param
| param type filter. Possible values returned in `/rest/params`. The parameter can appear multiple times, and the result will include procedures which contain all given parameter types.

| filter_loose
| whether enable loose filtering as described in <<Filtering logic>>

| return
| return type filter. Possible values returned in `/rest/returns`. The parameter can appear multiple times, and the result will include procedures which contain all given return types.
|===

JSON schema
[source,json]
----
{
    "type": "object",
    "properties": {
        "total": { "type": "integer" },
        "libs": { "$ref": "#/$defs/facet" },
        "params": { "$ref": "#/$defs/facet" },
        "returns": { "$ref": "#/$defs/facet" },
        "tags": { "$ref": "#/$defs/facet" },
        "items": {
            "type": "array",
            "items": { "$ref": "#/$defs/search-item" }
        }
    },
    "$defs": {
        "facet": {
            "type": "array",
            "items": { "$ref": "#/$defs/facet-value"}
        },
        "facet-value": {
            "type": "object",
            "properties": {
                "value": { "type": "string" },
                "count": { "type": "integer" }
            }
        },
        "search-item": {
            "type": "object",
            "properties": {
                "lib": { "type": "string" },
                "name": { "type": "string" },
                "param_names": { 
                    "type": "array",
                    "items": { "type": "string" }
                },
                "signature": { "type": "string" },
                "param_signatures": { "type": "string" },
                "syntax_param_signatures": { "type": "string" },
                "tags": { 
                    "type": "array",
                    "items": { "type": "string" }
                },
                "param_types": { 
                    "type": "array",
                    "items": { "type": "string" }
                },
                "return_types": { 
                    "type": "array",
                    "items": { "type": "string" }
                },
                "super_types": { 
                    "type": "array",
                    "items": { "type": "string" }
                }
            }
        }
    }
}
----

Example response

[source,json]
----
{"items":[{"lib":"(scheme base)","name":"*","param_names":["z"],"signature":"(lambda ((number? z) ...) number?)","param_signatures":"()","syntax_param_signatures":"()","tags":["pure"],"param_types":["number?"],"return_types":["number?"],"super_types":[]},{"lib":"(scheme base)","name":"+","param_names":["z"],"signature":"(lambda ((number? z) ...) number?)","param_signatures":"()","syntax_param_signatures":"()","tags":["pure"],"param_types":["number?"],"return_types":["number?"],"super_types":[]},{"lib":"(scheme base)","name":"-","param_names":["z"],"signature":"(lambda ((number? z) ...) number?)","param_signatures":"()","syntax_param_signatures":"()","tags":["pure"],"param_types":["number?"],"return_types":["number?"],"super_types":[]},{"lib":"(scheme base)","name":"\/","param_names":["z1","z2"],"signature":"(lambda ((number? z1) (number? z2) ...) number?)","param_signatures":"()","syntax_param_signatures":"()","tags":["pure"],"param_types":["number?","number?"],"return_types":["number?"],"super_types":[]},{"lib":"(scheme base)","name":"<","param_names":["x1","x2","x3"],"signature":"(lambda ((real? x1) (real? x2) (real? x3) ...) boolean?)","param_signatures":"()","syntax_param_signatures":"()","tags":["pure"],"param_types":["real?","real?","real?"],"return_types":["boolean?"],"super_types":[]}],"total":2170,"libs":[{"value":"(scheme base)","count":295},{"value":"(scheme bitwise)","count":41},{"value":"(scheme box)","count":4},{"value":"(scheme bytevector)","count":66},{"value":"(scheme case-lambda)","count":1},{"value":"(scheme char)","count":22},{"value":"(scheme charset)","count":73},{"value":"(scheme comparator)","count":35},{"value":"(scheme complex)","count":6},{"value":"(scheme cxr)","count":24},{"value":"(scheme division)","count":18},{"value":"(scheme ephemeron)","count":6},{"value":"(scheme eval)","count":2},{"value":"(scheme file)","count":10},{"value":"(scheme fixnum)","count":44},{"value":"(scheme flonum)","count":124},{"value":"(scheme generator)","count":55},{"value":"(scheme hash-table)","count":60},{"value":"(scheme ideque)","count":49},{"value":"(scheme ilist)","count":154},{"value":"(scheme inexact)","count":13},{"value":"(scheme lazy)","count":5},{"value":"(scheme list)","count":186},{"value":"(scheme list-queue)","count":27},{"value":"(scheme load)","count":2},{"value":"(scheme lseq)","count":30},{"value":"(scheme mapping hash)","count":72},{"value":"(scheme mapping)","count":104},{"value":"(scheme process-context)","count":7},{"value":"(scheme read)","count":2},{"value":"(scheme repl)","count":1},{"value":"(scheme rlist)","count":53},{"value":"(scheme set)","count":113},{"value":"(scheme show)","count":107},{"value":"(scheme sort)","count":50},{"value":"(scheme stream)","count":41},{"value":"(scheme text)","count":193},{"value":"(scheme time)","count":3},{"value":"(scheme vector)","count":64},{"value":"(scheme write)","count":8}],"params":[{"value":"bag?","count":56},{"value":"boolean?","count":20},{"value":"box?","count":2},{"value":"bytevector?","count":90},{"value":"char-set?","count":46},{"value":"char?","count":53},{"value":"circular-list?","count":11},{"value":"comparator?","count":65},{"value":"complex?","count":4},{"value":"dotted-ilist?","count":7},{"value":"dotted-list?","count":12},{"value":"ephemeron?","count":3},{"value":"error-object?","count":2},{"value":"fixnum?","count":36},{"value":"flonum?","count":77},{"value":"formatter","count":37},{"value":"hash-table?","count":43},{"value":"hashmap?","count":68},{"value":"ideque?","count":42},{"value":"ilist?","count":68},{"value":"input-port?","count":16},{"value":"integer?","count":498},{"value":"ipair?","count":46},{"value":"list-queue?","count":20},{"value":"list?","count":199},{"value":"lseq?","count":28},{"value":"mapping?","count":94},{"value":"number?","count":57},{"value":"output-port?","count":19},{"value":"pair?","count":89},{"value":"port?","count":2},{"value":"procedure?","count":503},{"value":"promise?","count":1},{"value":"rational?","count":2},{"value":"real?","count":29},{"value":"rlist?","count":8},{"value":"rpair?","count":33},{"value":"set?","count":46},{"value":"stream-pair?","count":2},{"value":"stream?","count":18},{"value":"string?","count":101},{"value":"symbol?","count":39},{"value":"text?","count":3},{"value":"textual?","count":158},{"value":"vector?","count":125}],"returns":[{"value":"bag?","count":37},{"value":"boolean?","count":264},{"value":"box?","count":1},{"value":"bytevector?","count":36},{"value":"char-set?","count":55},{"value":"char?","count":12},{"value":"circular-list?","count":7},{"value":"comparator?","count":23},{"value":"complex?","count":2},{"value":"dotted-ilist?","count":2},{"value":"dotted-list?","count":2},{"value":"eof-object?","count":17},{"value":"ephemeron?","count":1},{"value":"exact?","count":1},{"value":"fixnum?","count":24},{"value":"flonum?","count":99},{"value":"formatter","count":87},{"value":"formatter-variable","count":14},{"value":"hash-table?","count":17},{"value":"hashmap?","count":46},{"value":"ideque?","count":30},{"value":"ilist?","count":51},{"value":"inexact?","count":1},{"value":"input-port?","count":5},{"value":"integer?","count":207},{"value":"ipair?","count":12},{"value":"list-queue?","count":12},{"value":"list?","count":171},{"value":"lseq?","count":17},{"value":"mapping?","count":66},{"value":"number?","count":19},{"value":"output-port?","count":6},{"value":"pair?","count":15},{"value":"procedure?","count":52},{"value":"promise?","count":3},{"value":"rational?","count":1},{"value":"real?","count":12},{"value":"rlist?","count":8},{"value":"rpair?","count":3},{"value":"set?","count":29},{"value":"stream-null?","count":1},{"value":"stream-pair?","count":1},{"value":"stream?","count":24},{"value":"string?","count":44},{"value":"symbol?","count":2},{"value":"text?","count":89},{"value":"vector?","count":57}],"tags":[{"value":"deprecated","count":18},{"value":"parameter","count":3},{"value":"parameterized","count":24},{"value":"predicate","count":66},{"value":"pure","count":1564}]}
----

== STDIO API

When enabled (see <<Configuration>>), program starts a repl, reading request from standard input, and returning response in standard output. The exchange is very similar to REST api, just through different medium. Therefore this section only describes how to call it, for the response format see REST description.

Each call should be a list, where a `car` denotes the endpoint. Possible endpoint values: `tags`, `params`, `returns`, `libs`, `search`. First 4 endpoints do not take any parameters, therefore the call consists of a list of single element. `search` endpoint takes parameters by reading from alist in `cdr` position of the request list. Possible parameters : `start`, `rows`, `query`, `libs`, `param-types`, `return-types`, `tags`, `filter-param-loose?`.

The response scheme object denoting json (in accordance with srfi 180), returned as if with `write`. In case of an error, a list will be returned in a form of `(error <cause>)`.

Some examples

[source, scheme]
----
; request
(libs)

; response
#("(scheme base)")
----

[source, scheme]
----
; request
(search (rows . 1) (tags pure))

; response
((items . #(...)) (total . 2000) (libs . #(...)))
----

[source, scheme]
----
; request
(foo)

; response
(error "#<ERROR unknown request endpoint>")
----
