(
 
 ;; helper
 ((r7rsindex aux) . "types/r7rsindex.aux.scm")
 
 ;; r7rs small
 ((scheme base) . "types/scheme.base.scm")
 ((scheme case-lambda) . "types/scheme.case-lambda.scm")
 ((scheme complex) . "types/scheme.complex.scm")
 ((scheme char) . "types/scheme.char.scm")
 ((scheme cxr) . "types/scheme.cxr.scm")
 ((scheme eval) . "types/scheme.eval.scm")
 ((scheme file) . "types/scheme.file.scm")
 ((scheme inexact) . "types/scheme.inexact.scm")
 ((scheme lazy) . "types/scheme.lazy.scm")
 ((scheme load) . "types/scheme.load.scm")
 ((scheme process-context) . "types/scheme.process-context.scm")
 ((scheme read) . "types/scheme.read.scm")
 ((scheme repl) . "types/scheme.repl.scm")
 ((scheme time) . "types/scheme.time.scm")
 ((scheme write) . "types/scheme.write.scm")
 
 ; r7rs large red
 ((scheme box) . "types/scheme.box.scm")
 ((scheme comparator) . "types/scheme.comparator.scm")
 ((scheme charset) . "types/scheme.charset.scm")
 ((scheme ephemeron) . "types/scheme.ephemeron.scm")
 ((scheme generator) . "types/scheme.generator.scm")
 ((scheme hash-table) . "types/scheme.hash-table.scm")
 ((scheme ideque) . "types/scheme.ideque.scm")
 ((scheme ilist) . "types/scheme.ilist.scm")
 ((scheme list) . "types/scheme.list.scm")
 ((scheme list-queue) . "types/scheme.list-queue.scm")
 ((scheme lseq) . "types/scheme.lseq.scm")
 ((scheme rlist) . "types/scheme.rlist.scm")
 ((scheme set) . "types/scheme.set.scm")
 ((scheme stream) . "types/scheme.stream.scm")
 ((scheme sort) . "types/scheme.sort.scm")
 ((scheme text) . "types/scheme.text.scm")
 ((scheme vector) . "types/scheme.vector.scm")
 
 ; r7rs large tangerine
 ;((scheme bitwise) . "types/scheme.bitwise.scm")
 ;((scheme bytevector) . "types/scheme.bytevector.scm")
 ;((scheme division) . "types/scheme.division.scm")
 ;((scheme fixnum) . "types/scheme.fixnum.scm")
 ;((scheme flonum) . "types/scheme.flonum.scm")
 ;((scheme mapping) . "types/scheme.mapping.scm")
 ;((scheme mapping hash) . "types/scheme.mapping.hash.scm")
 ;((scheme regex) . "types/scheme.regex.scm")
 ;((scheme show) . "types/scheme.show.scm")
 ;((scheme vector base) . "types/scheme.vector.base.scm")
 ;((scheme vector u8) . "types/scheme.vector.u8.scm")
 ;((scheme vector s8) . "types/scheme.vector.s8.scm")
 ;((scheme vector u16) . "types/scheme.vector.u16.scm")
 ;((scheme vector s16) . "types/scheme.vector.s16.scm")
 ;((scheme vector u32) . "types/scheme.vector.u32.scm")
 ;((scheme vector s32) . "types/scheme.vector.s32.scm")
 ;((scheme vector u64) . "types/scheme.vector.u64.scm")
 ;((scheme vector s64) . "types/scheme.vector.s64.scm")
 ;((scheme vector f32) . "types/scheme.vector.f32.scm")
 ;((scheme vector f64) . "types/scheme.vector.f64.scm")
 ;((scheme vector c64) . "types/scheme.vector.c64.scm")
 ;((scheme vector c128) . "types/scheme.vector.c128.scm")
 
 )
