(
 ((scheme base) . "types/scheme.base.scm")
 ((scheme complex) . "types/scheme.complex.scm")
 ((scheme cxr) . "types/scheme.cxr.scm")
 ((scheme eval) . "types/scheme.eval.scm")
 ((scheme file) . "types/scheme.file.scm")
 ((scheme inexact) . "types/scheme.inexact.scm")
 ((scheme lazy) . "types/scheme.lazy.scm")
 ((scheme load) . "types/scheme.load.scm")
 ((scheme process-context) . "types/scheme.process-context.scm")
 ((scheme read) . "types/scheme.read.scm")
 ((scheme repl) . "types/scheme.repl.scm")
 ((scheme time) . "types/scheme.time.scm")
 ((scheme write) . "types/scheme.write.scm")
 )
