(

 ;; base
 ((name . *) (signature lambda ((number? z) ...) number?) (tags pure))
 ((name . +) (signature lambda ((number? z) ...) number?) (tags pure))
 ((name . -) (signature lambda ((number? z) ...) number?) (tags pure))
 ((name . /)
  (signature lambda ((number? z1) (number? z2) ...) number?)
  (tags pure))
 ((name . <)
  (signature lambda ((real? x1) (real? x2) (real? x3) ...) boolean?)
  (tags pure))
 ((name . <=)
  (signature lambda ((real? x1) (real? x2) (real? x3) ...) boolean?)
  (tags pure))
 ((name . =)
  (signature lambda ((number? z1) (number? z2) (number? z3) ...) boolean?)
  (tags pure))
 ((name . >)
  (signature lambda ((real? x1) (real? x2) (real? x3) ...) boolean?)
  (tags pure))
 ((name . >=)
  (signature lambda ((real? x1) (real? x2) (real? x3) ...) boolean?)
  (tags pure))
 ((name . abs) (signature lambda ((real? x)) number?) (tags pure))
 ((name . and) (signature syntax-rules () ((_ test1 ...))))
 ((name . append) (signature lambda ((list? list) ...) list?) (tags pure))
 ((name . append) (signature lambda ((list? list) ... obj) *) (tags pure))
 ((name . apply)
  (signature lambda ((procedure? proc) arg1 ... (list? args)) *)
  (tags pure))
 ((name . assoc)
  (signature lambda (obj (list? alist)) (or pair? #f))
  (tags pure))
 ((name . assq)
  (signature lambda (obj (list? alist)) (or pair? #f))
  (tags pure))
 ((name . assv)
  (signature lambda (obj (list? alist)) (or pair? #f))
  (tags pure))
 ((name . begin)
  (signature syntax-rules () ((_ expression-or-definition ...))))
 ((name . boolean?) (signature lambda (obj) boolean?) (tags pure predicate))
 ((name . caar) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . cadr) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . call-with-current-continuation)
  (signature lambda ((procedure? proc)) *)
  (subsigs (proc (lambda ((procedure? k)) *))))
 ((name . call-with-values)
  (signature lambda ((procedure? producer) (procedure? consumer)) *)
  (tags pure)
  (subsigs (producer (lambda () *)) (consumer (lambda (obj ...) *))))
 ((name . car) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . case)
  (signature syntax-rules (else) ((_ key clause1 clause2 ...)))
  (subsigs
   (clause
    ((datum1 ...) expression1 expression2 ...)
    (else expression1 expression2 ...))))
 ((name . cdar) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . cddr) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . cdr) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . ceiling) (signature lambda ((real? x)) real?) (tags pure))
 ((name . char->integer)
  (signature lambda ((char? char)) integer?)
  (tags pure))
 ((name . char-ready?) (signature lambda () boolean?))
 ((name . char-ready?) (signature lambda ((input-port? port)) boolean?))
 ((name . char<=?)
  (signature lambda ((char? char1) (char? char2) (char? char3) ...) boolean?)
  (tags pure))
 ((name . char<?)
  (signature lambda ((char? char1) (char? char2) (char? char3) ...) boolean?)
  (tags pure))
 ((name . char=?)
  (signature lambda ((char? char1) (char? char2) (char? char3) ...) boolean?)
  (tags pure))
 ((name . char>=?)
  (signature lambda ((char? char1) (char? char2) (char? char3) ...) boolean?)
  (tags pure))
 ((name . char>?)
  (signature lambda ((char? char1) (char? char2) (char? char3) ...) boolean?)
  (tags pure))
 ((name . char?) (signature lambda (obj) boolean?) (tags pure predicate))
 ((name . close-input-port) (signature lambda ((input-port? port)) undefined))
 ((name . close-output-port)
  (signature lambda ((output-port? port)) undefined))
 ((name . complex?)
  (signature lambda (obj) boolean?)
  (tags pure predicate)
  (subsigs)
  (supertypes number?))
 ((name . cond)
  (signature syntax-rules (else =>) ((_ clause1 clause2 ...)))
  (subsigs
   (clause
    (test expression1 ...)
    (test => receiver)
    (else expression1 expression2 ...)))
  (syntax-param-signatures
    (receiver procedure?)))
 ((name . cons) (signature lambda (obj1 obj2) pair?) (tags pure))
 ((name . current-input-port)
  (signature lambda () input-port?))
 ((name . current-output-port)
  (signature lambda () output-port?))
 ((name . define)
  (signature
   syntax-rules
   ()
   ((_ variable expression))
   ((_ (variable parameter1 ...) body))
   ((_ (variable parameter1 ... . parameter) body))))
 ((name . define-syntax)
  (signature syntax-rules () ((_ keyword transformer-spec)))
  (syntax-param-signatures (transformer-spec transformer-spec)))
 ((name . denominator) (signature lambda ((rational? q)) integer?) (tags pure))
 ((name . do)
  (signature
   syntax-rules
   ()
   ((_ (variable-decl1 ...) (test expression ...) command ...)))
  (subsigs (variable-decl (variable init step) (variable init))))
 ((name . dynamic-wind)
  (signature
   lambda
   ((procedure? before) (procedure? thunk) (procedure? after))
   *)
  (subsigs
   (before (lambda () undefined))
   (thunk (lambda () *))
   (after (lambda () undefined))))
 ((name . eof-object?) (signature lambda (obj) boolean?) (tags pure predicate))
 ((name . eq?) (signature lambda (obj1 obj2) boolean?) (tags pure))
 ((name . equal?) (signature lambda (obj1 obj2) boolean?) (tags pure))
 ((name . eqv?) (signature lambda (obj1 obj2) boolean?) (tags pure))
 ((name . even?)
  (signature lambda ((integer? n)) boolean?)
  (tags pure predicate))
 ((name . inexact->exact) (signature lambda ((number? z)) exact?) (tags pure))
 ((name . exact?)
  (signature lambda ((number? z)) boolean?)
  (tags pure)
  (subsigs)
  (supertypes number?))
 ((name . expt)
  (signature lambda ((number? z1) (number? z2)) number?)
  (tags pure))
 ((name . floor) (signature lambda ((real? x)) integer?) (tags pure))
 ((name . for-each)
  (signature
   lambda
   ((procedure? proc) (list? list1) (list? list2) ...)
   undefined)
  (subsigs (proc (lambda (obj1 obj2 ...) undefined))))
 ((name . gcd) (signature lambda ((integer? n) ...) integer?) (tags pure))
 ((name . if)
  (signature
   syntax-rules
   ()
   ((_ test consequent))
   ((_ test consequent alternate))))
 ((name . exact->inexact) (signature lambda ((number? z)) inexact?) (tags pure))
 ((name . inexact?)
  (signature lambda ((number? z)) boolean?)
  (tags pure)
  (subsigs)
  (supertypes number?))
 ((name . input-port?)
  (signature lambda (obj) boolean?)
  (tags pure predicate)
  (subsigs)
  (supertypes port?))
 ((name . integer->char) (signature lambda ((integer? n)) char?) (tags pure))
 ((name . integer?)
  (signature lambda (obj) boolean?)
  (tags pure predicate)
  (subsigs)
  (supertypes rational?))
 ((name . lambda)
  (signature syntax-rules () ((_ formals body) procedure?))
  (subsigs
   (formals
    (variable1 ...)
    variable
    (variable1 ... variable_n . variable_n+1))))
 ((name . lcm) (signature lambda ((integer? n) ...) integer?) (tags pure))
 ((name . length) (signature lambda ((list? list)) integer?) (tags pure))
 ((name . let)
  (signature syntax-rules () ((_ bindings body)))
  (subsigs (bindings ((variable1 init1) ...))))
 ((name . let*)
  (signature syntax-rules () ((_ bindings body)))
  (subsigs (bindings ((variable1 init1) ...))))
 ((name . let-syntax)
  (signature syntax-rules () ((_ bindings body)))
  (subsigs (bindings ((keyword transformer-spec) ...)))
  (syntax-param-signatures (transformer-spec transformer-spec)))
 ((name . letrec)
  (signature syntax-rules () ((_ bindings body)))
  (subsigs (bindings ((variable1 init1) ...))))
 ((name . letrec-syntax)
  (signature syntax-rules () ((_ bindings body)))
  (subsigs (bindings ((keyword transformer-spec) ...))))
 ((name . list) (signature lambda (obj ...) list?) (tags pure))
 ((name . list->string) (signature lambda ((list? list)) string?) (tags pure))
 ((name . list->vector) (signature lambda ((list? list)) vector?) (tags pure))
 ((name . list-ref)
  (signature lambda ((list? list) (integer? k)) *)
  (tags pure))
 ((name . list-tail)
  (signature lambda ((list? list) (integer? k)) list?)
  (tags pure))
 ((name . list?)
  (signature lambda (obj) boolean?)
  (tags pure predicate)
  (subsigs)
  (supertypes pair? null?))
 ((name . make-string) (signature lambda ((integer? k)) string?))
 ((name . make-string)
  (signature lambda ((integer? k) (char? char)) string?)
  (tags pure))
 ((name . make-vector) (signature lambda ((integer? k)) vector?))
 ((name . make-vector)
  (signature lambda ((integer? k) fill) vector?)
  (tags pure))
 ((name . map)
  (signature lambda ((procedure? proc) (list? list1) (list? list2) ...) list?)
  (tags pure)
  (subsigs (proc (lambda (obj1 obj2 ...) *))))
 ((name . max)
  (signature lambda ((real? x1) (real? x2) ...) real?)
  (tags pure))
 ((name . member)
  (signature lambda (obj (list? list)) (or #f list?))
  (tags pure))
 ((name . memq)
  (signature lambda (obj (list? list)) (or #f list?))
  (tags pure))
 ((name . memv)
  (signature lambda (obj (list? list)) (or #f list?))
  (tags pure))
 ((name . min)
  (signature lambda ((real? x1) (real? x2) ...) real?)
  (tags pure))
 ((name . modulo)
  (signature lambda ((integer? n1) (integer? n2)) integer?)
  (tags pure))
 ((name . negative?) (signature lambda ((real? x)) boolean?) (tags pure))
 ((name . newline) (signature lambda () undefined))
 ((name . newline) (signature lambda ((output-port? port)) undefined))
 ((name . not) (signature lambda (obj) boolean?) (tags pure))
 ((name . null?) (signature lambda (obj) boolean?) (tags pure predicate))
 ((name . number->string) (signature lambda ((number? z)) string?) (tags pure))
 ((name . number->string)
  (signature lambda ((number? z) (integer? radix)) string?)
  (tags pure))
 ((name . number?) (signature lambda (obj) boolean?) (tags pure predicate))
 ((name . numerator) (signature lambda ((rational? q)) integer?) (tags pure))
 ((name . odd?)
  (signature lambda ((integer? n)) boolean?)
  (tags pure predicate))
 ((name . or) (signature syntax-rules () ((_ test1 ...))))
 ((name . output-port?)
  (signature lambda (obj) boolean?)
  (tags pure predicate)
  (subsigs)
  (supertypes port?))
 ((name . pair?) (signature lambda (obj) boolean?) (tags pure predicate))
 ((name . peek-char)
  (signature lambda () (or eof-object? char?)))
 ((name . peek-char)
  (signature lambda ((input-port? port)) (or eof-object? char?)))
 ((name . port?) (signature lambda (obj) boolean?) (tags pure predicate))
 ((name . positive?) (signature lambda ((real? x)) boolean?) (tags pure))
 ((name . procedure?) (signature lambda (obj) boolean?) (tags pure predicate))
 ((name . quasiquote) (signature syntax-rules () ((_ qq-template))))
 ((name . quote) (signature syntax-rules () ((_ datum))))
 ((name . quotient)
  (signature lambda ((integer? n1) (integer? n2)) integer?)
  (tags pure))
 ((name . rational?)
  (signature lambda (obj) boolean?)
  (tags pure predicate)
  (subsigs)
  (supertypes real?))
 ((name . rationalize)
  (signature lambda ((real? x) (real? y)) rational?)
  (tags pure))
 ((name . read-char)
  (signature lambda () (or eof-object? char?)))
 ((name . read-char)
  (signature lambda ((input-port? port)) (or eof-object? char?)))
 ((name . real?)
  (signature lambda (obj) boolean?)
  (tags pure predicate)
  (subsigs)
  (supertypes complex?))
 ((name . remainder)
  (signature lambda ((integer? n1) (integer? n2)) integer?)
  (tags pure))
 ((name . reverse) (signature lambda ((list? list)) list?) (tags pure))
 ((name . round) (signature lambda ((real? x)) integer?) (tags pure))
 ((name . set!) (signature syntax-rules () ((_ variable expression))))
 ((name . set-car!) (signature lambda ((pair? pair) obj) undefined))
 ((name . set-cdr!) (signature lambda ((pair? pair) obj) undefined))
 ((name . string) (signature lambda ((char? char) ...) string?) (tags pure))
 ((name . string->list)
  (signature lambda ((string? string)) list?)
  (tags pure))
 ((name . string->number)
  (signature lambda ((string? string)) number?)
  (tags pure))
 ((name . string->number)
  (signature lambda ((string? string) (integer? radix)) number?)
  (tags pure))
 ((name . string->symbol)
  (signature lambda ((string? string)) symbol?)
  (tags pure))
 ((name . string-append)
  (signature lambda ((string? string) ...) string?)
  (tags pure))
 ((name . string-copy)
  (signature lambda ((string? string)) string?)
  (tags pure))
 ((name . string-fill!)
  (signature lambda ((string? string) (char? fill)) undefined))
 ((name . string-length)
  (signature lambda ((string? string)) integer?)
  (tags pure))
 ((name . string-ref)
  (signature lambda ((string? string) (integer? k)) char?)
  (tags pure))
 ((name . string-set!)
  (signature lambda ((string? string) (integer? k) (char? char)) undefined))
 ((name . string<=?)
  (signature
   lambda
   ((string? string1) (string? string2) (string? string3) ...)
   boolean?)
  (tags pure))
 ((name . string<?)
  (signature
   lambda
   ((string? string1) (string? string2) (string? string3) ...)
   boolean?)
  (tags pure))
 ((name . string=?)
  (signature
   lambda
   ((string? string1) (string? string2) (string? string3) ...)
   boolean?)
  (tags pure))
 ((name . string>=?)
  (signature
   lambda
   ((string? string1) (string? string2) (string? string3) ...)
   boolean?)
  (tags pure))
 ((name . string>?)
  (signature
   lambda
   ((string? string1) (string? string2) (string? string3) ...)
   boolean?)
  (tags pure))
 ((name . string?)
  (signature lambda (obj) boolean?)
  (tags pure predicate)
  (subsigs)
  (supertypes textual?))
 ((name . substring)
  (signature lambda ((string? string) (integer? start) (integer? end)) string?)
  (tags pure))
 ((name . symbol->string)
  (signature lambda ((symbol? symbol)) string?)
  (tags pure))
 ((name . symbol?) (signature lambda (obj) boolean?) (tags pure predicate))
 ((name . syntax-rules)
  (signature
   syntax-rules
   (_)
   ((_ (literal ...) syntax-rule ...) transformer-spec))
  (subsigs
   (syntax-rule (pattern template))
   (pattern
    _
    identifier
    constant
    (pattern ...)
    (pattern pattern ... . pattern)
    (pattern ... pattern ellipsis pattern ...)
    (pattern ... pattern ellipsis pattern ... . pattern)
    (_append "#" (pattern ...))
    (_append "#" (pattern ... pattern ellipsis pattern ...)))
   (template
    identifier
    constant
    (element ...)
    (element element ... . template)
    (ellipsis template)
    (_append "#" (element ...)))
   (element template (_append template ellipsis))))
 ((name . truncate) (signature lambda ((real? x)) integer?) (tags pure))
 ((name . unquote) (signature syntax-rules () ((_ expression))))
 ((name . unquote-splicing) (signature syntax-rules () ((_ expression))))
 ((name . values) (signature lambda (obj ...) (values * ...)) (tags pure))
 ((name . vector) (signature lambda (obj ...) vector?) (tags pure))
 ((name . vector->list)
  (signature lambda ((vector? vector)) list?)
  (tags pure))
 ((name . vector-fill!) (signature lambda ((vector? vector) fill) undefined))
 ((name . vector-length)
  (signature lambda ((vector? vector)) integer?)
  (tags pure))
 ((name . vector-ref)
  (signature lambda ((vector? vector) (integer? k)) *)
  (tags pure))
 ((name . vector-set!)
  (signature lambda ((vector? vector) (integer? k) obj) undefined))
 ((name . vector?) (signature lambda (obj) boolean?) (tags pure predicate))
 ((name . write-char)
  (signature lambda ((char? char)) undefined))
 ((name . write-char)
  (signature lambda ((char? char) (output-port? port)) undefined))
 ((name . zero?)
  (signature lambda ((number? z)) boolean?)
  (tags pure predicate))

 ;; complex
 ((name . angle) (signature lambda ((complex? z)) real?) (tags pure))
 ((name . imag-part) (signature lambda ((complex? z)) real?) (tags pure))
 ((name . magnitude) (signature lambda ((complex? z)) real?) (tags pure))
 ((name . make-polar)
  (signature lambda ((real? x3) (real? x4)) complex?)
  (tags pure))
 ((name . make-rectangular)
  (signature lambda ((real? x1) (real? x2)) complex?)
  (tags pure))
 ((name . real-part) (signature lambda ((complex? z)) real?) (tags pure))

 ;;char
 ((name . char-alphabetic?)
  (signature lambda ((char? char)) boolean?)
  (tags pure))
 ((name . char-ci<=?)
  (signature lambda ((char? char1) (char? char2) (char? char3) ...) boolean?)
  (tags pure))
 ((name . char-ci<?)
  (signature lambda ((char? char1) (char? char2) (char? char3) ...) boolean?)
  (tags pure))
 ((name . char-ci=?)
  (signature lambda ((char? char1) (char? char2) (char? char3) ...) boolean?)
  (tags pure))
 ((name . char-ci>=?)
  (signature lambda ((char? char1) (char? char2) (char? char3) ...) boolean?)
  (tags pure))
 ((name . char-ci>?)
  (signature lambda ((char? char1) (char? char2) (char? char3) ...) boolean?)
  (tags pure))
 ((name . char-downcase) (signature lambda ((char? char)) char?) (tags pure))
 ((name . char-lower-case?)
  (signature lambda ((char? char)) boolean?)
  (tags pure))
 ((name . char-numeric?)
  (signature lambda ((char? char)) boolean?)
  (tags pure))
 ((name . char-upcase) (signature lambda ((char? char)) char?) (tags pure))
 ((name . char-upper-case?)
  (signature lambda ((char? char)) boolean?)
  (tags pure))
 ((name . char-whitespace?)
  (signature lambda ((char? char)) boolean?)
  (tags pure))
 ((name . string-ci<=?)
  (signature
   lambda
   ((string? string1) (string? string2) (string? string3) ...)
   boolean?)
  (tags pure))
 ((name . string-ci<?)
  (signature
   lambda
   ((string? string1) (string? string2) (string? string3) ...)
   boolean?)
  (tags pure))
 ((name . string-ci=?)
  (signature
   lambda
   ((string? string1) (string? string2) (string? string3) ...)
   boolean?)
  (tags pure))
 ((name . string-ci>=?)
  (signature
   lambda
   ((string? string1) (string? string2) (string? string3) ...)
   boolean?)
  (tags pure))
 ((name . string-ci>?)
  (signature
   lambda
   ((string? string1) (string? string2) (string? string3) ...)
   boolean?)
  (tags pure))

 ;; cxr
 ((name . caaaar) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . caaadr) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . caaar) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . caadar) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . caaddr) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . caadr) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . cadaar) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . cadadr) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . cadar) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . caddar) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . cadddr) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . caddr) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . cdaaar) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . cdaadr) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . cdaar) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . cdadar) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . cdaddr) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . cdadr) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . cddaar) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . cddadr) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . cddar) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . cdddar) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . cddddr) (signature lambda ((pair? pair)) *) (tags pure))
 ((name . cdddr) (signature lambda ((pair? pair)) *) (tags pure))

 ;;eval
 ((name . eval) (signature lambda (expr-or-def (environment environment-specifier)) *))
 ((name . scheme-report-environment) (signature lambda ((integer? version)) environment))
 ((name . null-environment) (signature lambda ((integer? version)) environment))
 
 ;; inexact
 ((name . acos) (signature lambda ((number? z)) number?) (tags pure))
 ((name . asin) (signature lambda ((number? z)) number?) (tags pure))
 ((name . atan) (signature lambda ((number? z)) number?) (tags pure))
 ((name . atan) (signature lambda ((real? y) (real? x)) number?) (tags pure))
 ((name . cos) (signature lambda ((number? z)) number?) (tags pure))
 ((name . exp) (signature lambda ((number? z)) number?) (tags pure))
 ((name . log) (signature lambda ((number? z)) number?) (tags pure))
 ((name . sin) (signature lambda ((number? z)) number?) (tags pure))
 ((name . sqrt) (signature lambda ((number? z)) number?) (tags pure))
 ((name . tan) (signature lambda ((number? z)) number?) (tags pure))

 ;; file
 ((name . call-with-input-file)
  (signature lambda ((string? string) (procedure? proc)) *)
  (subsigs (proc (lambda ((input-port? port)) *))))
 ((name . call-with-output-file)
  (signature lambda ((string? string) (procedure? proc)) *)
  (subsigs (proc (lambda ((output-port? port)) *))))
 ((name . open-input-file) (signature lambda ((string? string)) input-port?))
 ((name . open-output-file) (signature lambda ((string? string)) output-port?))
 ((name . with-input-from-file)
  (signature lambda ((string? string) (procedure? thunk)) *)
  (subsigs (thunk (lambda () *))))
 ((name . with-output-to-file)
  (signature lambda ((string? string) (procedure? thunk)) *)
  (subsigs (thunk (lambda () *))))

 ;; lazy
 ((name . delay) (signature syntax-rules () ((_ expression) promise?)))
 ((name . force) (signature lambda ((promise? promise)) *))

 ;; load
 ((name . load) (signature lambda ((string? filename)) undefined))

 ;; read
 ((name . read) (signature lambda () *))
 ((name . read) (signature lambda ((input-port? port)) *))

 ;;transcript
 ((name . transcript-on) (signature lambda ((string? filename)) undefined))
 ((name . transcript-off) (signature lambda () undefined))

 ;; write
 ((name . display) (signature lambda (obj) undefined))
 ((name . display) (signature lambda (obj (output-port? port)) undefined))
 ((name . write) 
  (signature lambda (obj) undefined))
 ((name . write) (signature lambda (obj (output-port? port)) undefined))

)
