(((name . "record?") (signature lambda (obj) boolean?) (tags pure))
 ((name . "record-rtd")
  (signature lambda ((record? record)) record-type-descriptor?)
  (tags pure))
 ((name . "record-type-name")
  (signature lambda ((record-type-descriptor? rtd)) symbol?)
  (tags pure))
 ((name . "record-type-parent")
  (signature
   lambda
   ((record-type-descriptor? rtd))
   (or #f record-type-descriptor?))
  (tags pure))
 ((name . "record-type-uid")
  (signature lambda ((record-type-descriptor? rtd)) (or symbol? #f))
  (tags pure))
 ((name . "record-type-generative?")
  (signature lambda ((record-type-descriptor? rtd)) boolean?)
  (tags pure))
 ((name . "record-type-sealed?")
  (signature lambda ((record-type-descriptor? rtd)) boolean?)
  (tags pure))
 ((name . "record-type-opaque?")
  (signature lambda ((record-type-descriptor? rtd)) boolean?)
  (tags pure))
 ((name . "record-type-field-names")
  (signature lambda ((record-type-descriptor? rtd)) vector?)
  (tags pure))
 ((name . "record-field-mutable?")
  (signature lambda ((record-type-descriptor? rtd) (integer? k)) boolean?)
  (tags pure)))
