(((name . "char-alphabetic?")
  (signature lambda ((char? char)) boolean?)
  (tags pure))
 ((name . "char-ci<=?")
  (signature lambda ((char? char1) (char? char2) (char? char3) ...) boolean?)
  (tags pure))
 ((name . "char-ci<?")
  (signature lambda ((char? char1) (char? char2) (char? char3) ...) boolean?)
  (tags pure))
 ((name . "char-ci=?")
  (signature lambda ((char? char1) (char? char2) (char? char3) ...) boolean?)
  (tags pure))
 ((name . "char-ci>=?")
  (signature lambda ((char? char1) (char? char2) (char? char3) ...) boolean?)
  (tags pure))
 ((name . "char-ci>?")
  (signature lambda ((char? char1) (char? char2) (char? char3) ...) boolean?)
  (tags pure))
 ((name . "char-downcase") (signature lambda ((char? char)) char?) (tags pure))
 ((name . "char-foldcase") (signature lambda ((char? char)) char?) (tags pure))
 ((name . "char-general-category")
  (signature lambda ((char? char)) symbol?)
  (tags pure))
 ((name . "char-lower-case?")
  (signature lambda ((char? char)) boolean?)
  (tags pure))
 ((name . "char-numeric?")
  (signature lambda ((char? char)) boolean?)
  (tags pure))
 ((name . "char-titlecase")
  (signature lambda ((char? char)) char?)
  (tags pure))
 ((name . "char-title-case?")
  (signature lambda ((char? char)) boolean?)
  (tags pure))
 ((name . "char-upcase") (signature lambda ((char? char)) char?) (tags pure))
 ((name . "char-upper-case?")
  (signature lambda ((char? char)) boolean?)
  (tags pure))
 ((name . "char-whitespace?")
  (signature lambda ((char? char)) boolean?)
  (tags pure))
 ((name . "string-ci<=?")
  (signature
   lambda
   ((string? string1) (string? string2) (string? string3) ...)
   boolean?)
  (tags pure))
 ((name . "string-ci<?")
  (signature
   lambda
   ((string? string1) (string? string2) (string? string3) ...)
   boolean?)
  (tags pure))
 ((name . "string-ci=?")
  (signature
   lambda
   ((string? string1) (string? string2) (string? string3) ...)
   boolean?)
  (tags pure))
 ((name . "string-ci>=?")
  (signature
   lambda
   ((string? string1) (string? string2) (string? string3) ...)
   boolean?)
  (tags pure))
 ((name . "string-ci>?")
  (signature
   lambda
   ((string? string1) (string? string2) (string? string3) ...)
   boolean?)
  (tags pure))
 ((name . "string-downcase")
  (signature lambda ((string? string)) string?)
  (tags pure))
 ((name . "string-foldcase")
  (signature lambda ((string? string)) string?)
  (tags pure))
 ((name . "string-normalize-nfd")
  (signature lambda ((string? string)) string?)
  (tags pure))
 ((name . "string-normalize-nfkd")
  (signature lambda ((string? string)) string?)
  (tags pure))
 ((name . "string-normalize-nfc")
  (signature lambda ((string? string)) string?)
  (tags pure))
 ((name . "string-normalize-nfkc")
  (signature lambda ((string? string)) string?)
  (tags pure))
 ((name . "string-titlecase")
  (signature lambda ((string? string)) string?)
  (tags pure))
 ((name . "string-upcase")
  (signature lambda ((string? string)) string?)
  (tags pure)))
