(((name . make-record-type-descriptor)
  (signature lambda ((symbol? name) 
                     ((or #f record-type-descriptor?) parent) 
                     ((or #f symbol?) uid) 
                     (boolean? sealed?) 
                     (boolean? opaque?) 
                     (vector? fields)) 
             record-type-descriptor?))
 ((name . record-type-descriptor?)
  (signature lambda (obj) boolean?)
  (tags pure predicate))
 ((name . make-record-constructor-descriptor)
  (signature lambda ((record-type-descriptor? rtd) ((or constructor-descriptor #f) parent-constructor-descriptor) ((or #f procedure?) protocol)) constructor-descriptor)
  (subsigs
    (protocol (lambda ((procedure? p)) procedure?))))
 ((name . record-constructor)
  (signature lambda ((constructor-descriptor constructor-descriptor)) procedure?))
 ((name . record-predicate)
  (signature lambda ((record-type-descriptor? rtd)) procedure?)
  (subsigs
    (return (lambda (obj) boolean?))))
 ((name . record-accessor)
  (signature lambda ((record-type-descriptor? rtd) (integer? k)) procedure?)
  (subsigs
    (return (lambda (record) *))))
 ((name . record-mutator)
  (signature lambda ((record-type-descriptor? rtd) (integer? k)) procedure?)
  (subsigs
    (return (lambda (record obj) undefined)))))
