(((name . "bitwise-not")
  (signature lambda ((integer? i)) integer?)
  (tags pure))
 ((name . "bitwise-and")
  (signature lambda ((integer? i) ...) integer?)
  (tags pure))
 ((name . "bitwise-ior")
  (signature lambda ((integer? i) ...) integer?)
  (tags pure))
 ((name . "bitwise-xor")
  (signature lambda ((integer? i) ...) integer?)
  (tags pure))
 ((name . "bitwise-if")
  (signature lambda ((integer? mask) (integer? i) (integer? j)) integer?)
  (tags pure))
 ((name . "bitwise-bit-count")
  (signature lambda ((integer? i)) integer?)
  (tags pure))
 ((name . "bitwise-length")
  (signature lambda ((integer? i)) integer?)
  (tags pure))
 ((name . "bitwise-first-bit-set")
  (signature lambda ((integer? i)) integer?)
  (tags pure))
 ((name . "bitwise-bit-set?")
  (signature lambda ((integer? i) (integer? index)) boolean?)
  (tags pure))
 ((name . "bitwise-copy-bit")
  (signature lambda ((integer? i) (integer? index) (integer? from)) integer?)
  (tags pure))
 ((name . "bitwise-bit-field")
  (signature lambda ((integer? i) (integer? start) (integer? end)) integer?)
  (tags pure))
 ((name . "bitwise-copy-bit-field")
  (signature
   lambda
   ((integer? i) (integer? start) (integer? end) (integer? from))
   integer?)
  (tags pure))
 ((name . "bitwise-arithmetic-shift")
  (signature lambda ((integer? i) (integer? count)) integer?)
  (tags pure))
 ((name . "bitwise-arithmetic-shift-left")
  (signature lambda ((integer? i) (integer? count)) integer?)
  (tags pure))
 ((name . "bitwise-arithmetic-shift-right")
  (signature lambda ((integer? i) (integer? count)) integer?)
  (tags pure))
 ((name . "bitwise-rotate-bit-field")
  (signature
   lambda
   ((integer? i) (integer? from) (integer? to) (integer? count))
   integer?)
  (tags pure))
 ((name . "bitwise-reverse-bit-field")
  (signature lambda ((integer? i) (integer? from) (integer? to)) integer?)
  (tags pure)))
