(((name . "command-line") (signature lambda () list?) (tags pure))
 ((name . "emergency-exit")
  (signature case-lambda (() undefined) ((obj) undefined)))
 ((name . "exit") (signature case-lambda (() undefined) ((obj) undefined)))
 ((name . "get-environment-variable")
  (signature lambda ((string? name)) (or string? #f))
  (tags pure))
 ((name . "get-environment-variables")
  (signature lambda () list?)
  (tags pure)))
