(((name . display) (signature lambda (obj) undefined) (tags parameterized))
 ((name . display) (signature lambda (obj (output-port? port)) undefined))
 ((name . write) (signature lambda (obj) undefined) (tags parameterized))
 ((name . write) (signature lambda (obj (output-port? port)) undefined))
 ((name . write-shared)
  (signature lambda (obj) undefined)
  (tags parameterized))
 ((name . write-shared) (signature lambda (obj (output-port? port)) undefined))
 ((name . write-simple)
  (signature lambda (obj) undefined)
  (tags parameterized))
 ((name . write-simple)
  (signature lambda (obj (output-port? port)) undefined)))
