(((name . "caaaar")
  (signature lambda ((pair? pair)) *)
  (tags pure)
  (desc . "Composition of car, car, car, car."))
 ((name . "caaadr")
  (signature lambda ((pair? pair)) *)
  (tags pure)
  (desc . "Composition of car, car, car, cdr."))
 ((name . "caaar")
  (signature lambda ((pair? pair)) *)
  (tags pure)
  (desc . "Composition of car, car, car."))
 ((name . "caadar")
  (signature lambda ((pair? pair)) *)
  (tags pure)
  (desc . "Composition of car, car, cdr, car."))
 ((name . "caaddr")
  (signature lambda ((pair? pair)) *)
  (tags pure)
  (desc . "Composition of car, car, cdr, cdr."))
 ((name . "caadr")
  (signature lambda ((pair? pair)) *)
  (tags pure)
  (desc . "Composition of car, car, cdr."))
 ((name . "cadaar")
  (signature lambda ((pair? pair)) *)
  (tags pure)
  (desc . "Composition of car, cdr, car, car."))
 ((name . "cadadr")
  (signature lambda ((pair? pair)) *)
  (tags pure)
  (desc . "Composition of car, cdr, car, cdr."))
 ((name . "cadar")
  (signature lambda ((pair? pair)) *)
  (tags pure)
  (desc . "Composition of car, cdr, car."))
 ((name . "caddar")
  (signature lambda ((pair? pair)) *)
  (tags pure)
  (desc . "Composition of car, cdr, cdr, car."))
 ((name . "cadddr")
  (signature lambda ((pair? pair)) *)
  (tags pure)
  (desc . "Composition of car, cdr, cdr, cdr."))
 ((name . "caddr")
  (signature lambda ((pair? pair)) *)
  (tags pure)
  (desc . "Composition of car, cdr, cdr."))
 ((name . "cdaaar")
  (signature lambda ((pair? pair)) *)
  (tags pure)
  (desc . "Composition of cdr, car, car, car."))
 ((name . "cdaadr")
  (signature lambda ((pair? pair)) *)
  (tags pure)
  (desc . "Composition of cdr, car, car, cdr."))
 ((name . "cdaar")
  (signature lambda ((pair? pair)) *)
  (tags pure)
  (desc . "Composition of cdr, car, car."))
 ((name . "cdadar")
  (signature lambda ((pair? pair)) *)
  (tags pure)
  (desc . "Composition of cdr, car, cdr, car."))
 ((name . "cdaddr")
  (signature lambda ((pair? pair)) *)
  (tags pure)
  (desc . "Composition of cdr, car, cdr, cdr."))
 ((name . "cdadr")
  (signature lambda ((pair? pair)) *)
  (tags pure)
  (desc . "Composition of cdr, car, cdr."))
 ((name . "cddaar")
  (signature lambda ((pair? pair)) *)
  (tags pure)
  (desc . "Composition of cdr, cdr, car, car."))
 ((name . "cddadr")
  (signature lambda ((pair? pair)) *)
  (tags pure)
  (desc . "Composition of cdr, cdr, car, cdr."))
 ((name . "cddar")
  (signature lambda ((pair? pair)) *)
  (tags pure)
  (desc . "Composition of cdr, cdr, car."))
 ((name . "cdddar")
  (signature lambda ((pair? pair)) *)
  (tags pure)
  (desc . "Composition of cdr, cdr, cdr, car."))
 ((name . "cddddr")
  (signature lambda ((pair? pair)) *)
  (tags pure)
  (desc . "Composition of cdr, cdr, cdr, cdr."))
 ((name . "cdddr")
  (signature lambda ((pair? pair)) *)
  (tags pure)
  (desc . "Composition of cdr, cdr, cdr.")))
