(((name . "call-with-input-file")
  (signature lambda ((string? string) (procedure? proc)) *)
  (subsigs (proc (lambda ((input-port? port)) *))))
 ((name . "call-with-output-file")
  (signature lambda ((string? string) (procedure? proc)) *)
  (subsigs (proc (lambda ((output-port? port)) *))))
 ((name . "delete-file") (signature lambda ((string? filename)) undefined))
 ((name . "file-exists?") (signature lambda ((string? filename)) boolean?))
 ((name . "open-binary-input-file")
  (signature lambda ((string? string)) input-port?))
 ((name . "open-binary-output-file")
  (signature lambda ((string? string)) output-port?))
 ((name . "open-input-file") (signature lambda ((string? string)) input-port?))
 ((name . "open-output-file")
  (signature lambda ((string? string)) output-port?))
 ((name . "with-input-from-file")
  (signature lambda ((string? string) (procedure? thunk)) *)
  (subsigs (thunk (lambda () *))))
 ((name . "with-output-to-file")
  (signature lambda ((string? string) (procedure? thunk)) *)
  (subsigs (thunk (lambda () *)))))
