(((name . "command-line") (signature lambda () list?) (tags pure))
 ((name . "emergency-exit") (signature lambda () undefined))
 ((name . "emergency-exit") (signature lambda (obj) undefined))
 ((name . "exit") (signature lambda () undefined))
 ((name . "exit") (signature lambda (obj) undefined))
 ((name . "get-environment-variable")
  (signature lambda ((string? name)) (or string? #f))
  (tags pure))
 ((name . "get-environment-variables")
  (signature lambda () list?)
  (tags pure)))
