(((name . "angle") (signature lambda ((complex? z)) real?) (tags pure))
 ((name . "imag-part") (signature lambda ((complex? z)) real?) (tags pure))
 ((name . "magnitude") (signature lambda ((complex? z)) real?) (tags pure))
 ((name . "make-polar")
  (signature lambda ((real? x3) (real? x4)) complex?)
  (tags pure))
 ((name . "make-rectangular")
  (signature lambda ((real? x1) (real? x2)) complex?)
  (tags pure))
 ((name . "real-part") (signature lambda ((complex? z)) real?) (tags pure)))
