(((name . "char-title-case?")
  (signature lambda ((char? char)) boolean?)
  (tags pure)
  (desc . "Returns #t if char is a character belonging to the Unicode category Lt, and #f otherwise. (The same as the R6RS equivalent.)"))
 ((name . "char-titlecase")
  (signature lambda ((char? char)) char?)
  (tags pure)
  (desc . "Returns the titlecase equivalent of char, if that character exists in the implementation, and char otherwise. The titlecase equivalent of a character is typically not a titlecase character; for most characters it is the same as the uppercase equivalent or else the character itself. Note that language-sensitive mappings are not used. (The same as the R6RS equivalent.)"))
 ((name . "string-titlecase")
  (signature lambda ((string? string)) string?)
  (tags pure)
  (desc . "This procedure applies the Unicode full string lowercasing algorithm to its argument. However, any character preceded by a non-cased character, or which is the first character of string, is processed by a different algorithm. If such a character has a multi-character titlecase mapping specified by Unicode, and all the characters of the mapping are supported by the implementation, then it is replaced by that mapping. Otherwise, it is replaced by its single-character titlecase mapping as if by char-titlecase. The result of the application of these algorithms is returned.
In certain cases, the result differs in length from the argument. If the result is equal to the argument in the sense of string=?, the argument may be returned. Note that language-sensitive mappings are not used. (The R6RS version does not make use of multi-character mappings.)")))
