(((name . "open-input-string")
  (signature lambda ((string? string)) input-port?)
  (tags pure)
  (desc . "Takes a string and returns a textual input port that delivers characters from the string. If the string is modified, the effect is unspecified."))
 ((name . "open-output-string") (signature lambda () output-port?) (tags pure) (desc . "Returns a textual output port that will accumulate characters for retrieval by get-output-string."))
 ((name . "get-output-string")
  (signature lambda ((output-port? port)) string?)
  (desc . "It is an error if port was not created with open-output-string. Returns a string consisting of the characters that have been output to the port so far in the order they were output. If the result string is modified, the effect is unspecified.")))
