(((name . "check-arg")
  (signature syntax-rules ()
             ((_ (procedure? predicate) arg caller))
             ((_ (procedure? predicate) arg)))
  (desc . "Guarantees that the arg (evaluated) conforms to the predicate (evaluated). Implementations can enforce the predicate check in all the code that follows, but are not required to. It is an error if predicate returns #f when called on arg. Otherwise, return value is unspecified. Implementations may use optional caller (evaluated) argument as the error who/origin if/when signaling a checking error."))
 ((name . "values-checked")
  (signature syntax-rules ()
             ((_ (predicates ...) values ...)))
  (desc . "Guarantees that the values (evaluated) abide by the given predicates (the number of values and predicates should match) and returns them as multiple values. It is an error if any of the predicates returns false. Implementations may choose to coerce the values when the types are compatible (e.g. integer -> inexact)."))
 ((name . "check-case")
  (signature syntax-rules (=> else) ((_ key clause1 clause2 ...)))
  (subsigs
   (clause
    (pattern
     (predicate expression1 expression2 ...)
     (else expression1 expression2 ...))))
  (desc . "check-case checks whether the value satisfies one of the predicates. If any of the predicates is satisfied, it evaluates the body corresponding to the first one that is satisfied. If none of the predicates is satisfied and there’s an else clause, it evaluates to the body of that clause; and if there’s it is an error if there’s no else clause and no other clause is satisfied."))
 ((name . "lambda-checked")
  (signature syntax-rules (=>)
             ((_ args ... => (returns ...) body)
              procedure?)
             ((_ args ... body)
              procedure?))
  (desc . "A regular lambda, but with any argument (except the rest argument) optionally having the form (name predicate) (as compared to default single-symbol form). Arguments of this extended form are guaranteed to satisfy the respective (evaluated) predicate. At least on procedure application time. This guarantee might be extended for all the procedure body, including for any modification and shadowing, at implementors' will. It is an error if either of the arguments does not satisfy the predicate."))
 ((name . "case-lambda-checked")
  (signature syntax-rules (=>)
             ((_ clause1 clause2 ...)
              procedure?))
  (subsigs
   (clause
    (pattern
     (() body ...)
     (() => (returns ...) body ...)
     (arg body ...)
     (arg => (returns ...) body ...)
     ((arg . args) body ...)
     ((arg . args) => (returns ...) body ...))))
  (desc . "Same as case-lambda, but with any argument taking a form of (name predicate) to be checked. See lambda-checked for other details."))
 ((name . "define-checked")
  (signature syntax-rules (=>)
             ((_ (name . args) body ...)
              procedure?)
             ((_ (name . args) => (returns...) body ...)
              procedure?)
             ((_ name predicate value)))
  (desc . "Defines a procedure or variable satisfying the given predicates. For procedures, effectively equal to define+lambda-checked. For variables, checks the value (and, if implementation supports that, all the subsequent modifications) for the predicate match."))
 ((name . "define-record-type-checked")
  (signature syntax-rules ()
             ((type-name (constructor ...) predicate clause1 clause2 ...)))
  (subsigs
   (clause
    (pattern
     (name (procedure? predicate) accessor)
     (name (procedure? predicate) accessor modifier))))
  (desc . "Defines a record type with checked constructor and field accessors/modifiers. type-name, constructor, and predicate are the same as R7RS define-record-type's (note especially the constructor—checks are not allowed in it, only arg-name symbols!) Fields are either of the form (field-name predicate accessor-name) or (field-name predicate accessor-name modifier-name). These ensure that accessor and modifier return checked data and check new data respectively. It is an error if any of the checks are not successful.")))
