(((name . "make-list-queue")
  (signature
   case-lambda
   (((list? list)) list-queue?)
   (((list? list) (pair? last)) list-queue?))
  (tags pure))
 ((name . "list-queue")
  (signature
   case-lambda
   ((element ...) list-queue?)
   (((list-queue? list-queue)) list-queue?))
  (tags pure))
 ((name . "list-queue-unfold")
  (signature
   case-lambda
   (((procedure? stop?) (procedure? mapper) (procedure? successor) seed)
    list-queue?)
   (((procedure? stop?)
     (procedure? mapper)
     (procedure? successor)
     seed
     (list-queue? queue))
    list-queue?))
  (subsigs
   (stop? (lambda (seed) boolean?))
   (mapper (lambda (seed) *))
   (successor (lambda (seed) *)))
  (tags pure))
 ((name . "list-queue-unfold-right")
  (signature
   case-lambda
   (((procedure? stop?) (procedure? mapper) (procedure? successor) seed)
    list-queue?)
   (((procedure? stop?)
     (procedure? mapper)
     (procedure? successor)
     seed
     (list-queue? queue))
    list-queue?))
  (subsigs
   (stop? (lambda (seed) boolean?))
   (mapper (lambda (seed) *))
   (successor (lambda (seed) *)))
  (tags pure))
 ((name . "list-queue?")
  (signature lambda (obj) boolean?)
  (tags pure predicate))
 ((name . "list-queue-empty?")
  (signature lambda ((list-queue? list-queue)) boolean?)
  (tags pure))
 ((name . "list-queue-front")
  (signature lambda ((list-queue? list-queue)) *)
  (tags pure))
 ((name . "list-queue-back")
  (signature lambda ((list-queue? list-queue)) *)
  (tags pure))
 ((name . "list-queue-list")
  (signature lambda ((list-queue? list-queue)) list?)
  (tags pure))
 ((name . "list-queue-first-last")
  (signature lambda ((list-queue? list-queue)) (values list? list?))
  (tags pure))
 ((name . "list-queue-add-front!")
  (signature lambda ((list-queue? list-queue) element) undefined))
 ((name . "list-queue-add-back!")
  (signature lambda ((list-queue? list-queue) element) undefined))
 ((name . "list-queue-remove-front!")
  (signature lambda ((list-queue? list-queue)) *))
 ((name . "list-queue-remove-back!")
  (signature lambda ((list-queue? list-queue)) *))
 ((name . "list-queue-remove-all!")
  (signature lambda ((list-queue? list-queue)) list?))
 ((name . "list-queue-set-list!")
  (signature
   case-lambda
   (((list-queue? list-queue) (list? list)) undefined)
   (((list-queue? list-queue) (list? list) (pair? last)) undefined)))
 ((name . "list-queue-append")
  (signature lambda ((list-queue? list-queue) ...) list-queue?)
  (tags pure))
 ((name . "list-queue-append!")
  (signature lambda ((list-queue? list-queue) ...) list-queue?))
 ((name . "list-queue-concatenate")
  (signature lambda ((list? list-of-list-queues)) list-queue?)
  (tags pure))
 ((name . "list-queue-map")
  (signature lambda ((procedure? proc) (list-queue? list-queue)) list-queue?)
  (subsigs (proc (lambda (element) *)))
  (tags pure))
 ((name . "list-queue-map!")
  (signature lambda ((procedure? proc) (list-queue? list-queue)) undefined)
  (subsigs (proc (lambda (element) *))))
 ((name . "list-queue-for-each")
  (signature lambda ((procedure? proc) (list-queue? list-queue)) undefined)
  (subsigs (proc (lambda (element) undefined)))))
