(((name . "delay") (signature syntax-rules () ((_ expression) promise?)))
 ((name . "lazy")
  (signature syntax-rules () ((_ expression) promise?))
  (subsigs (expression (value promise?))))
 ((name . "force") (signature lambda ((promise? expression)) *))
 ((name . "eager") (signature lambda (expression) promise?)))
