(((name . "keyword?")
  (signature lambda (obj) boolean?)
  (tags pure predicate)
  (desc . "Returns #t if obj is a keyword object, otherwise returns #f."))
 ((name . "keyword->string")
  (signature lambda ((keyword? keyword)) string?)
  (tags pure predicate)
  (desc . "Returns the name of keyword as a string. It is an error to apply mutation procedures like string-set! to strings returned by this procedure."))
 ((name . "string->keyword")
  (signature lambda ((string? string)) keyword?)
  (tags pure predicate)
  (desc . "Returns the keyword object whose name is string.")))
