(((name . "implementation-name")
  (signature lambda () (or string? #f))
  (tags pure))
 ((name . "implementation-version")
  (signature lambda () (or string? #f))
  (tags pure))
 ((name . "cpu-architecture")
  (signature lambda () (or string? #f))
  (tags pure))
 ((name . "machine-name") (signature lambda () (or string? #f)) (tags pure))
 ((name . "os-name") (signature lambda () (or string? #f)) (tags pure))
 ((name . "os-version") (signature lambda () (or string? #f)) (tags pure)))
