(((name . "box")
  (signature lambda (value) box?)
  (tags pure)
  (desc . "Constructor. Returns a newly allocated box initialized to value."))
 ((name . "box?") (signature lambda (object) boolean?) (tags pure predicate)
  (desc . "Predicate. Returns #t if object is a box, and #f otherwise."))
 ((name . "unbox") (signature lambda ((box? box)) *) (tags pure)
  (desc . "Accessor. Returns the current value of box."))
 ((name . "set-box!") (signature lambda ((box? box) value) undefined)
  (desc . "Mutator. Changes box to hold value.")))
