(((name . make-rtd)
  ;; TODO document fieldspecs content
  (signature lambda ((symbol? name) (vector? fieldspecs)) rtd?)
  (tags pure))
 ((name . make-rtd)
  (signature lambda ((symbol? name) (vector? fieldspecs) ((or rtd? #f) parent)) rtd?)
  (tags pure))
 ((name . rtd?)
  (signature lambda (obj) boolean?)
  (tags pure predicate))
 ((name . rtd-constructor)
  (signature lambda ((rtd? rtd)) procedure?)
  (subsigs
    (return (lambda (fieldvalue ...) record?)))
  (tags pure))
 ((name . rtd-constructor)
  (signature lambda ((rtd? rtd) (vector? fieldspec)) procedure?)
  (tags pure)
  (subsigs
    (return (lambda (fieldvalue ...) record?))))
 ((name . rtd-predicate)
  (signature lambda ((rtd? rtd)) procedure?)
  (tags pure)
  (subsigs
    (return (lambda (obj) boolean?))))
 ((name . rtd-accessor)
  (signature lambda ((rtd? rtd) (symbol? field)) procedure?)
  (tags pure)
  (subsigs
    (return (lambda ((record? rec)) *))))
 ((name . rtd-mutator)
  (signature lambda ((rtd? rtd) (symbol? field)) procedure?)
  (tags pure)
  (subsigs
    (return (lambda ((record? rec) value) undefined)))))
