(

 ((name . s32vector?)
  (signature lambda (obj) boolean?)
  (tags pure predicate))
 ((name . make-s32vector)
  (signature lambda ((integer? size)) s32vector?))
 ((name . make-s32vector)
  (signature lambda ((integer? size) (integer? fill)) s32vector?)
  (tags pure))
 ((name . s32vector-length)
  (signature lambda ((s32vector? vec)) integer?)
  (tags pure))
 ((name . s32vector-ref)
  (signature lambda ((s32vector? vec) (integer? i)) integer?)
  (tags pure))
 ((name . s32vector-set!)
  (signature lambda ((s32vector? vec) (integer? i) (integer? value)) undefined))
 ((name . s32vector->list)
  (signature lambda ((s32vector? vec)) list?)
  (tags pure))
 ((name . list->s32vector)
  (signature lambda ((list? proper-list)) s32vector?)
  (tags pure))

)
