(((name . "record?") (signature lambda (obj) boolean?) (tags pure predicate) (desc . "Equivalent to its R6RS namesake."))
 ((name . "record-rtd") (signature lambda ((record? rec)) rtd?) (tags pure) (desc . "Equivalent to its R6RS namesake."))
 ((name . "rtd-name") (signature lambda ((rtd? rtd)) symbol?) (tags pure) (desc . "Equivalent to the record-type-name procedure of the R6RS."))
 ((name . "rtd-parent")
  (signature lambda ((rtd? rtd)) (or #f rtd?))
  (tags pure)
  (desc . "Equivalent to the record-type-parent procedure of the R6RS."))
 ((name . "rtd-field-names")
  (signature lambda ((rtd? rtd)) vector?)
  (tags pure)
  (desc . "Equivalent to the record-type-field-names procedure of the R6RS. (That is, it returns a vector of the symbols that name the fields of the record-type represented by rtd, excluding the fields of parent record-types.)"))
 ((name . "rtd-all-field-names")
  (signature lambda ((rtd? rtd)) vector?)
  (tags pure)
  (desc . "Returns a vector of the symbols that name the fields of the record-type represented by rtd, including the fields of its parent record-types, if any. The fields of parent record-types come before the fields of its children, with each subsequence in the same order as in the vectors that would be returned by calling rtd-field-names on rtd and on all its ancestral record-type descriptors."))
 ((name . "rtd-field-mutable?")
  (signature lambda ((rtd? rtd) (symbol? field)) boolean?)
  (tags pure)
  (desc . "rtd is a record-type descriptor, and field is a symbol naming a field of the record-type described by rtd. Returns #t if the named field is mutable; otherwise returns #f.")))
