(((name . "array?") (signature lambda (obj) boolean?) (tags predicate pure))
 ((name . "make-array")
  (signature
   case-lambda
   (((array? shape)) array?)
   (((array? shape) obj) array?))
  (tags pure))
 ((name . "shape")
  (signature lambda ((integer? lowerbound1) (integer? upperbound1) ...) array?)
  (tags pure))
 ((name . "array")
  (signature lambda ((array? shape) obj ...) array?)
  (tags pure))
 ((name . "array-rank")
  (signature lambda ((array? shape)) integer?)
  (tags pure))
 ((name . "array-start")
  (signature lambda ((array? shape) (integer? k)) integer?)
  (tags pure))
 ((name . "array-end")
  (signature lambda ((array? shape) (integer? k)) integer?)
  (tags pure))
 ((name . "array-ref")
  (signature
   case-lambda
   (((array? shape) (integer? k) ...) *)
   (((array? shape) ((or vector? array?) index)) *))
  (tags pure))
 ((name . "array-set!")
  (signature
   case-lambda
   (((array? shape) (integer? k) ... obj) undefined)
   (((array? shape) ((or vector? array?) index) obj) undefined)))
 ((name . "share-array")
  (signature lambda ((array? array) (array? shape) (procedure? proc)) array?)
  (subsigs (proc (lambda ((integer? index1) ...) (values integer? ...))))
  (tags pure)))
