(((name . "constantly")
  (signature lambda (obj ...) procedure?)
  (desc . "Returns the objs as its values, ignoring args."))
 ((name . "complement")
  (signature lambda ((procedure? proc)) procedure?)
  (subsigs (proc (lambda (x) boolean?)))
  (desc . "Returns #t when (proc obj) returns #f, and #f otherwise."))
 ((name . "flip")
  (signature lambda ((procedure? proc)) procedure?)
  (subsigs (proc (lambda (objs ...) *)))
  (desc . "Returns what (apply proc (reverse objs)) returns."))
 ((name . "swap")
  (signature lambda ((procedure? proc)) procedure?)
  (subsigs (proc (lambda (x y rest ...) *)))
  (desc . "Returns (apply proc obj₂ obj₁ objs)."))
 ((name . "on-left")
  (signature lambda ((procedure? proc)) procedure?)
  (subsigs (proc (lambda (x) *)))
  (desc . "Returns (proc obj₁)."))
 ((name . "on-right")
  (signature lambda ((procedure? proc)) procedure?)
  (subsigs (proc (lambda (x) *)))
  (desc . "Returns (proc obj₂)."))
 ((name . "conjoin")
  (signature lambda ((procedure? proc) ...) procedure?)
  (subsigs (proc (lambda (arg ...) boolean?)))
  (desc . "The predicates are applied in turn to the args as follows: If a call to a predicate returns false, no more predicates are applied and #f is returned. If all predicates return true, then the last value is returned. If there are no predicates, #t is returned."))
 ((name . "disjoin")
  (signature lambda ((procedure? proc) ...) procedure?)
  (subsigs (proc (lambda (arg ...) boolean?)))
  (desc . "The predicates are applied in turn to the args as follows: If a call to a predicate returns true, no more predicates are applied and its value is returned. If all predicates return false, then the last value is returned. If there are no predicates, #f is returned."))
 ((name . "each-of")
  (signature lambda ((procedure? proc) ...) procedure?)
  (subsigs (proc (lambda (arg ...) *)))
  (desc . "Applies each of the procs in turn to args, discarding the results and returning an unspecified value."))
 ((name . "all-of")
  (signature lambda ((procedure? proc)) procedure?)
  (subsigs (proc (lambda ((list? list)) *)))
  (desc . "Applies predicate to each element of list in turn, and immediately returns #f if predicate is not satisfied by that element. If every element satisfies predicate, returns the result of the last call to predicate. If list is empty, returns #t."))
 ((name . "any-of")
  (signature lambda ((procedure? proc)) procedure?)
  (subsigs (proc (lambda ((list? list)) *)))
  (desc . "

Applies predicate to each element of list in turn, and if predicate is satisfied by that element, immediately returns the result of calling predicate. If no element satisfies predicate returns #f. If list is empty, returns #f."))
 ((name . "on")
  (signature lambda ((procedure? reducer) (procedure? mapper)) procedure?)
  (subsigs (reducer (lambda (a b) *))
           (mapper (lambda (x) *)))
  (desc . "Applies mapper to each obj in any order and then applies reducer to all of the results in left to right order."))
 ((name . "left-section")
  (signature lambda ((procedure? proc) arg ...) procedure?)
  (subsigs (proc (lambda (obj ...) *)))
  (desc . "Applies proc to args concatenated with objs."))
 ((name . "right-section")
  (signature lambda ((procedure? proc) arg ...) procedure?)
  (subsigs (proc (lambda (obj ...) *)))
  (desc . "Applies proc to objs concatenated with the value of (reverse args)."))
 ((name . "apply-chain")
  (signature lambda ((procedure? proc) ...) procedure?)
  (subsigs (proc (lambda (obj ...) *)))
  (desc . "Applies the last proc to args returning zero or more values, then applies the previous proc to the values, returning more values, until the first proc has been invoked; its values are returned. For example, (apply-chain car cdr) returns a procedure that behaves like cadr:"))
 ((group ((name . "arguments-drop")
          (signature lambda ((procedure? proc) (integer? n)) procedure?)
          (subsigs (proc (lambda (obj ...) *))))
         ((name . "arguments-drop-right")
          (signature lambda ((procedure? proc) (integer? n)) procedure?)
          (subsigs (proc (lambda (obj ...) *))))
         ((name . "arguments-take")
          (signature lambda ((procedure? proc) (integer? n)) procedure?)
          (subsigs (proc (lambda (obj ...) *))))
         ((name . "arguments-take-right")
          (signature lambda ((procedure? proc) (integer? n)) procedure?)
          (subsigs (proc (lambda (obj ...) *)))))
  (desc "Apply proc to the args after taking/dropping n arguments from args."))
 ((name . "group-by")
  (signature case-lambda
             (((procedure? key-proc)) list?)
             (((procedure? key-proc) (procedure? =)) list?))
  (subsigs (key-proc (lambda (obj) *))
           (= (lambda (a b) boolean?)))
  (desc . "Takes the elements of list and applies key-proc to each of them to get their keys. Elements whose keys are the same (in the sense of =, which defaults to equal?) are grouped into newly allocated lists, and a list of these lists is returned. Within each list, the elements appear in the same order as they do in list; in addition, the first elements of each list also appear in the same order as they do in list. If list is the empty list, it is returned."))
 ;; Syntax-like procedures
 ((name . "begin-procedure")
  (signature lambda ((procedure? thunk) ...) *)
  (subsigs (thunk (lambda () *)))
  (desc . "Invokes thunks in order, and returns what the last thunk returns, or an unspecified value if there are no thunks."))
 ((name . "if-procedure")
  (signature lambda (value (procedure? then-thunk) (procedure? else-thunk)) *)
  (subsigs (then-thunk (lambda () *))
           (else-thunk (lambda () *)))
  (desc . "If value is true, invokes then-thunk and returns what it returns. Otherwise, invokes else-thunk and returns what it returns."))
 ((group ((name . "when-procedure")
          (signature lambda (value (procedure? thunk) ...) undefined)
          (subsigs (thunk (lambda () *))))
         ((name . "unless-procedure")
          (signature lambda (value (procedure? thunk) ...) undefined)
          (subsigs (thunk (lambda () *)))))
  (desc . "If value is false/true, immediately returns. Otherwise, invokes each thunk in turn and then returns. In all cases an unspecified value is returned."))
 ((name . "value-procedure")
  (signature lambda (value (procedure? then-thunk) (procedure? else-thunk)) *)
  (subsigs (then-thunk (lambda (value) *))
           (else-thunk (lambda () *)))
  (desc . "If value is true, invokes then-thunk and returns what it returns. Otherwise, invokes else-thunk and returns what it returns."))
 ((name . "case-procedure")
  (signature case-lambda
             ((value (list? thunk-alist)) undefined)
             ((value (list? thunk-alist) (procedure? else-thunk)) undefined))
  (subsigs (thunk-alist (alist * procedure?))
           (else-thunk (lambda () *)))
  (desc . "Searches thunk-alist for value (as if by assv). If there is a matching entry in thunk-alist, its cdr is invoked as a thunk, and case-procedure returns what the thunk returns. If there is no such entry in thunk-alist, invokes else-thunk (if present) and returns what it returns. If else-thunk is not present, the result is undefined."))
 ((name . "and-procedure")
  (signature lambda ((procedure? thunk) ...) *)
  (subsigs (thunk (lambda () *)))
  (desc . "The thunks are invoked from left to right, and if any thunk returns false, then #f is returned. Any remaining thunks are not invoked. If all the thunks return true values, the values of the last thunk are returned. If there are no thunks, then #t is returned."))
 ((name . "eager-and-procedure")
  (signature lambda ((procedure? thunk) ...) *)
  (subsigs (thunk (lambda () *)))
  (desc . "All the thunks are invoked from left to right. If any thunk returns false, then #f is returned. If all the thunks return true values, the value of the last thunk is returned. If there are no thunks, then #t is returned."))
 ((name . "or-procedure")
  (signature lambda ((procedure? thunk) ...) *)
  (subsigs (thunk (lambda () *)))
  (desc . "The thunks are invoked from left to right, and the first true value is returned. Any remaining thunks are not invoked. If all thunks return #f or if there are no thunks, then #f is returned."))
 ((name . "eager-or-procedure")
  (signature lambda ((procedure? thunk) ...) *)
  (subsigs (thunk (lambda () *)))
  (desc . "All the thunks are invoked from left to right, and then the first true value is returned. If all thunks return #f or if there are no thunks, then #f is returned."))
 ((name . "funcall-procedure")
  (signature lambda ((procedure? thunk)) *)
  (subsigs (thunk (lambda () *)))
  (desc . "Invokes thunk once, and returns what it returns."))
 ((name . "loop-procedure")
  (signature lambda ((procedure? thunk)) *)
  (subsigs (thunk (lambda () *)))
  (desc . "Invokes thunk repeatedly. Does not return unless via call/cc."))
 ((name . "while-procedure")
  (signature lambda ((procedure? thunk)) *)
  (subsigs (thunk (lambda () *)))
  (desc . "Invokes thunk repeatedly until it returns false. Returns an unspecified value."))
 ((name . "until-procedure")
  (signature lambda ((procedure? thunk)) *)
  (subsigs (thunk (lambda () *)))
  (desc . "Invokes thunk repeatedly until it returns true. Returns an unspecified value."))
 ;; Other procedures
 ((name . "always")
  (signature lambda (arg ...) boolean?)
  (desc . "Ignores its arguments and always returns #t."))
 ((name . "never")
  (signature lambda (arg ...) #f)
  (desc . "Ignores its arguments and always returns #f."))
 ((name . "boolean")
  (signature lambda (obj) boolean?)
  (desc . "If obj is true, returns #t; otherwise returns #f.")))
