(((name . command-line)
  (signature lambda () list?)
  (tags pure))
 ((name . command-name)
  (signature lambda () (or string? #f))
  (tags pure))
 ((name . script-file)
  (signature lambda () (or string? #f))
  (tags pure))
 ((name . script-directory)
  (signature lambda () (or string? #f))
  (tags pure)))
