(((name . "current-language")
  (signature case-lambda (() symbol?) (((symbol? lang)) undefined)))
 ((name . "current-country")
  (signature case-lambda (() symbol?) (((symbol? country)) undefined)))
 ((name . "current-locale-details")
  (signature case-lambda (() list?) (((list? symbols)) undefined)))
 ((name . "declare-bundle!")
  (signature lambda ((list? bundle-specifier) (list? alist)) undefined))
 ((name . "store-bundle")
  (signature lambda ((list? bundle-specifier)) boolean?))
 ((name . "load-bundle!")
  (signature lambda ((list? bundle-specifier)) boolean?))
 ((name . "localized-template")
  (signature
   lambda
   ((symbol? package-name) (symbol? message-tpl-name))
   (or string? #f))))
