(((name . "f32vector?")
  (signature lambda (obj) boolean?)
  (tags pure predicate)
  (desc . "Returns #t if the if an object is homogenous f32vector, #f otherwise."))
 ((name . "make-f32vector")
  (signature
   case-lambda
   (((integer? size)) f32vector?)
   (((integer? size) (real? fill)) f32vector?))
  (tags pure)
  (desc . "Create homogenous f32 vector. If fill is given, it must be inexact real. If fill isn't given, vector is filled with unspecified values which are guaranteed to fit into the range of the f32vector."))
 ((name . "f32vector")
  (signature lambda ((real? value) ...) f32vector?)
  (tags pure)
  (desc . "Create homogenous f32 vector. Each value must be inexact real."))
 ((name . "f32vector-length")
  (signature lambda ((f32vector? vec)) integer?)
  (tags pure)
  (desc . "Returns the number of elements in f32vector as an exact integer."))
 ((name . "f32vector-ref")
  (signature lambda ((f32vector? vec) (integer? i)) real?)
  (tags pure)
  (desc . "Returns i-th element in the vector. i must be in range [0, (f32vector-length vec))"))
 ((name . "f32vector-set!")
  (signature lambda ((f32vector? vec) (integer? i) (real? value)) undefined)
  (desc . "f32vector-set! stores value in element k of vector. Value must be inexact real. i must be in range [0, (f32vector-length vec))"))
 ((name . "f32vector->list")
  (signature lambda ((f32vector? vec)) list?)
  (tags pure)
  (desc . "Converts a homogenous vector to a list."))
 ((name . "list->f32vector")
  (signature lambda ((list? proper-list)) f32vector?)
  (subsigs
    (proper-list (list real?)))
  (tags pure)
  (desc . "Converts a list to a homogenous f32vector. Each element in input list must be inexact real.")))
