(((name . "u32vector?")
  (signature lambda (obj) boolean?)
  (tags pure predicate)
  (desc . "Returns #t if the if an object is homogenous u32vector, #f otherwise."))
 ((name . "make-u32vector")
  (signature
   case-lambda
   (((integer? size)) u32vector?)
   (((integer? size) (integer? fill)) u32vector?))
  (tags pure)
  (desc . "Create homogenous u32 vector. If fill is given, it must be unsigned exact integer in the range 0 to (2^32)-1. If fill isn't given, vector is filled with unspecified values which are guaranteed to fit into the range of the u32vector."))
 ((name . "u32vector")
  (signature lambda ((integer? value) ...) u32vector?)
  (tags pure)
  (desc . "Create homogenous u32 vector. Each value must be unsigned exact integer in the range 0 to (2^32)-1."))
 ((name . "u32vector-length")
  (signature lambda ((u32vector? vec)) integer?)
  (tags pure)
  (desc . "Returns the number of elements in u32vector as an exact integer."))
 ((name . "u32vector-ref")
  (signature lambda ((u32vector? vec) (integer? i)) integer?)
  (tags pure)
  (desc . "Returns i-th element in the vector. i must be in range [0, (u32vector-length vec))"))
 ((name . "u32vector-set!")
  (signature lambda ((u32vector? vec) (integer? i) (integer? value)) undefined)
  (desc . "u32vector-set! stores value in element k of vector. Value must be unsigned exact integer in the range 0 to (2^32)-1. i must be in range [0, (u32vector-length vec))"))
 ((name . "u32vector->list")
  (signature lambda ((u32vector? vec)) list?)
  (tags pure)
  (desc . "Converts a homogenous vector to a list."))
 ((name . "list->u32vector")
  (signature lambda ((list? proper-list)) u32vector?)
  (subsigs
    (proper-list (list integer?)))
  (tags pure)
  (desc . "Converts a list to a homogenous u32vector. Each element in input list must be unsigned exact integer in the range 0 to (2^32)-1.")))
