(((name . "u32vector?")
  (signature lambda (obj) boolean?)
  (tags pure predicate))
 ((name . "make-u32vector")
  (signature
   case-lambda
   (((integer? size)) u32vector?)
   (((integer? size) (integer? fill)) u32vector?))
  (tags pure))
 ((name . "u32vector-length")
  (signature lambda ((u32vector? vec)) integer?)
  (tags pure))
 ((name . "u32vector-ref")
  (signature lambda ((u32vector? vec) (integer? i)) integer?)
  (tags pure))
 ((name . "u32vector-set!")
  (signature
   lambda
   ((u32vector? vec) (integer? i) (integer? value))
   undefined))
 ((name . "u32vector->list")
  (signature lambda ((u32vector? vec)) list?)
  (tags pure))
 ((name . "list->u32vector")
  (signature lambda ((list? proper-list)) u32vector?)
  (tags pure)))
