(((name . "u8vector?")
  (signature lambda (obj) boolean?)
  (tags pure predicate)
  (desc . "Returns #t if the if an object is homogenous u8vector, #f otherwise."))
 ((name . "make-u8vector")
  (signature
   case-lambda
   (((integer? size)) u8vector?)
   (((integer? size) (integer? fill)) u8vector?))
  (tags pure)
  (desc . "Create homogenous u8 vector. If fill is given, it must be unsigned exact integer in the range 0 to (2^8)-1. If fill isn't given, vector is filled with unspecified values which are guaranteed to fit into the range of the u8vector."))
 ((name . "u8vector")
  (signature lambda ((integer? value) ...) u8vector?)
  (tags pure)
  (desc . "Create homogenous u8 vector. Each value must be unsigned exact integer in the range 0 to (2^8)-1."))
 ((name . "u8vector-length")
  (signature lambda ((u8vector? vec)) integer?)
  (tags pure)
  (desc . "Returns the number of elements in u8vector as an exact integer."))
 ((name . "u8vector-ref")
  (signature lambda ((u8vector? vec) (integer? i)) integer?)
  (tags pure)
  (desc . "Returns i-th element in the vector. i must be in range [0, (u8vector-length vec))"))
 ((name . "u8vector-set!")
  (signature lambda ((u8vector? vec) (integer? i) (integer? value)) undefined)
  (desc . "u8vector-set! stores value in element k of vector. Value must be unsigned exact integer in the range 0 to (2^8)-1. i must be in range [0, (u8vector-length vec))"))
 ((name . "u8vector->list")
  (signature lambda ((u8vector? vec)) list?)
  (tags pure)
  (desc . "Converts a homogenous vector to a list."))
 ((name . "list->u8vector")
  (signature lambda ((list? proper-list)) u8vector?)
  (subsigs
    (proper-list (list integer?)))
  (tags pure)
  (desc . "Converts a list to a homogenous u8vector. Each element in input list must be unsigned exact integer in the range 0 to (2^8)-1.")))
