(((name . "random-integer") (signature lambda ((integer? n)) integer?))
 ((name . "random-real") (signature lambda () real?))
 ((name . "default-random-source") (signature value random-source?))
 ((name . "make-random-source") (signature lambda () random-source?))
 ((name . "random-source?")
  (signature lambda (obj) boolean?)
  (tags pure predicate))
 ((name . "random-source-state-ref")
  (signature lambda ((random-source? s)) random-source-state))
 ((name . "random-source-state-set!")
  (signature
   lambda
   ((random-source? s) (random-source-state state))
   undefined))
 ((name . "random-source-randomize!")
  (signature lambda ((random-source? s)) undefined))
 ((name . "random-source-pseudo-randomize!")
  (signature lambda ((random-source? s) (integer? i) (integer? j)) undefined))
 ((name . "random-source-make-integers")
  (signature lambda ((random-source? s)) procedure?)
  (subsigs (return (lambda ((integer? n)) integer?))))
 ((name . "random-source-make-reals")
  (signature lambda ((random-source? s) (real? unit)) procedure?)
  (subsigs (return (lambda () real?)))))
