(((name . "string?") (signature lambda (obj) boolean?) (tags pure predicate))
 ((name . "string-null?")
  (signature lambda ((string? s)) boolean?)
  (tags pure))
 ((name . "string-every")
  (signature
   case-lambda
   ((((or char? char-set? procedure?) c) (string? s)) *)
   ((((or char? char-set? procedure?) c) (string? s) (integer? start)) *)
   ((((or char? char-set? procedure?) c)
     (string? s)
     (integer? start)
     (integer? end))
    *))
  (subsigs (c (lambda ((char? char)) *)))
  (tags pure))
 ((name . "string-any")
  (signature
   case-lambda
   ((((or char? char-set? procedure?) c) (string? s)) *)
   ((((or char? char-set? procedure?) c) (string? s) (integer? start)) *)
   ((((or char? char-set? procedure?) c)
     (string? s)
     (integer? start)
     (integer? end))
    *))
  (subsigs (c (lambda ((char? char)) *)))
  (tags pure))
 ((name . "make-string")
  (signature
   case-lambda
   (((integer? k)) string?)
   (((integer? k) (char? char)) string?))
  (tags pure))
 ((name . "string") (signature lambda ((char? char) ...) string?) (tags pure))
 ((name . "string-tabulate")
  (signature lambda ((procedure? proc) (integer? len)) string?)
  (subsigs (proc (lambda ((integer? index)) char?)))
  (tags pure))
 ((name . "string->list")
  (signature
   case-lambda
   (((string? string)) list?)
   (((string? string) (integer? start)) list?)
   (((string? string) (integer? start) (integer? end)) list?))
  (tags pure))
 ((name . "list->string")
  (signature lambda ((list? list)) string?)
  (tags pure))
 ((name . "reverse-list->string")
  (signature lambda ((list? list)) string?)
  (tags pure))
 ((name . "string-join")
  (signature
   case-lambda
   (((list? string-list)) string?)
   (((list? string-list) (string? delimiter)) string?)
   (((list? string-list) (string? delimiter) (symbol? grammar)) string?))
  (tags pure)
  (spec-values
   (grammar
    ("'infix"
     "infix or separator grammar: insert the delimiter between list elements. An empty list will produce an empty string -- note, however, that parsing an empty string with an infix or separator grammar is ambiguous. Is it an empty list, or a list of one element, the empty string?")
    ("'strict-infix"
     "same as 'infix, but will raise an error if given an empty list.")
    ("'suffix"
     "suffix or terminator grammar: insert the delimiter after every list element. This grammar has no ambiguities.")
    ("'prefix"
     "prefix grammar: insert the delimiter before every list element. This grammar has no ambiguities."))))
 ((name . "string-length")
  (signature lambda ((string? string)) integer?)
  (tags pure))
 ((name . "string-ref")
  (signature lambda ((string? string) (integer? k)) char?)
  (tags pure))
 ((name . "string-copy")
  (signature
   case-lambda
   (((string? string)) string?)
   (((string? string) (integer? start)) string?)
   (((string? string) (integer? start) (integer? end)) string?))
  (tags pure))
 ((name . "substring/shared")
  (signature
   case-lambda
   (((string? string)) string?)
   (((string? string) (integer? start)) string?)
   (((string? string) (integer? start) (integer? end)) string?))
  (tags pure))
 ((name . "string-copy!")
  (signature
   case-lambda
   (((string? to) (integer? at) (string? from)) undefined)
   (((string? to) (integer? at) (string? from) (integer? start)) undefined)
   (((string? to) (integer? at) (string? from) (integer? start) (integer? end))
    undefined)))
 ((name . "string-take")
  (signature lambda ((string? s) (integer? nchars)) string?)
  (tags pure))
 ((name . "string-drop")
  (signature lambda ((string? s) (integer? nchars)) string?)
  (tags pure))
 ((name . "string-take-right")
  (signature lambda ((string? s) (integer? nchars)) string?)
  (tags pure))
 ((name . "string-drop-right")
  (signature lambda ((string? s) (integer? nchars)) string?)
  (tags pure))
 ((name . "string-pad")
  (signature
   case-lambda
   (((string? s) (integer? len)) string?)
   (((string? s) (integer? len) (char? char)) string?)
   (((string? s) (integer? len) (char? char) (integer? start)) string?)
   (((string? s) (integer? len) (char? char) (integer? start) (integer? end))
    string?))
  (tags pure))
 ((name . "string-pad-right")
  (signature
   case-lambda
   (((string? s) (integer? len)) string?)
   (((string? s) (integer? len) (char? char)) string?)
   (((string? s) (integer? len) (char? char) (integer? start)) string?)
   (((string? s) (integer? len) (char? char) (integer? start) (integer? end))
    string?))
  (tags pure))
 ((name . "string-trim")
  (signature
   case-lambda
   ((((or char? char-set? procedure?) c) (string? s)) string?)
   ((((or char? char-set? procedure?) c) (string? s) (integer? start)) string?)
   ((((or char? char-set? procedure?) c)
     (string? s)
     (integer? start)
     (integer? end))
    string?))
  (subsigs (c (lambda ((char? char)) *)))
  (tags pure))
 ((name . "string-trim-right")
  (signature
   case-lambda
   ((((or char? char-set? procedure?) c) (string? s)) string?)
   ((((or char? char-set? procedure?) c) (string? s) (integer? start)) string?)
   ((((or char? char-set? procedure?) c)
     (string? s)
     (integer? start)
     (integer? end))
    string?))
  (subsigs (c (lambda ((char? char)) *)))
  (tags pure))
 ((name . "string-trim-both")
  (signature
   case-lambda
   ((((or char? char-set? procedure?) c) (string? s)) string?)
   ((((or char? char-set? procedure?) c) (string? s) (integer? start)) string?)
   ((((or char? char-set? procedure?) c)
     (string? s)
     (integer? start)
     (integer? end))
    string?))
  (subsigs (c (lambda ((char? char)) *)))
  (tags pure))
 ((name . "string-set!")
  (signature lambda ((string? string) (integer? k) (char? char)) undefined))
 ((name . "string-fill!")
  (signature
   case-lambda
   (((string? string) (char? fill)) undefined)
   (((string? string) (char? fill) (integer? start)) undefined)
   (((string? string) (char? fill) (integer? start) (integer? end))
    undefined)))
 ((name . "string-compare")
  (signature
   case-lambda
   (((string? s1)
     (string? s2)
     (procedure? proc<)
     (procedure? proc=)
     (procedure? proc>))
    *)
   (((string? s1)
     (string? s2)
     (procedure? proc<)
     (procedure? proc=)
     (procedure? proc>)
     (integer? start1))
    *)
   (((string? s1)
     (string? s2)
     (procedure? proc<)
     (procedure? proc=)
     (procedure? proc>)
     (integer? start1)
     (integer? end1))
    *)
   (((string? s1)
     (string? s2)
     (procedure? proc<)
     (procedure? proc=)
     (procedure? proc>)
     (integer? start1)
     (integer? end1)
     (integer? start2))
    *)
   (((string? s1)
     (string? s2)
     (procedure? proc<)
     (procedure? proc=)
     (procedure? proc>)
     (integer? start1)
     (integer? end1)
     (integer? start2)
     (integer? end2))
    *))
  (subsigs
   (proc< (lambda ((integer? index)) *))
   (proc= (lambda ((integer? index)) *))
   (proc> (lambda ((integer? index)) *)))
  (tags pure))
 ((name . "string-compare-ci")
  (signature
   case-lambda
   (((string? s1)
     (string? s2)
     (procedure? proc<)
     (procedure? proc=)
     (procedure? proc>))
    *)
   (((string? s1)
     (string? s2)
     (procedure? proc<)
     (procedure? proc=)
     (procedure? proc>)
     (integer? start1))
    *)
   (((string? s1)
     (string? s2)
     (procedure? proc<)
     (procedure? proc=)
     (procedure? proc>)
     (integer? start1)
     (integer? end1))
    *)
   (((string? s1)
     (string? s2)
     (procedure? proc<)
     (procedure? proc=)
     (procedure? proc>)
     (integer? start1)
     (integer? end1)
     (integer? start2))
    *)
   (((string? s1)
     (string? s2)
     (procedure? proc<)
     (procedure? proc=)
     (procedure? proc>)
     (integer? start1)
     (integer? end1)
     (integer? start2)
     (integer? end2))
    *))
  (subsigs
   (proc< (lambda ((integer? index)) *))
   (proc= (lambda ((integer? index)) *))
   (proc> (lambda ((integer? index)) *)))
  (tags pure))
 ((name . "string=")
  (signature
   case-lambda
   (((string? s1) (string? s2)) boolean?)
   (((string? s1) (string? s2) (integer? start1)) boolean?)
   (((string? s1) (string? s2) (integer? start1) (integer? end1)) boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2))
    boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2)
     (integer? end2))
    boolean?))
  (tags pure))
 ((name . "string<>")
  (signature
   case-lambda
   (((string? s1) (string? s2)) boolean?)
   (((string? s1) (string? s2) (integer? start1)) boolean?)
   (((string? s1) (string? s2) (integer? start1) (integer? end1)) boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2))
    boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2)
     (integer? end2))
    boolean?))
  (tags pure))
 ((name . "string<")
  (signature
   case-lambda
   (((string? s1) (string? s2)) boolean?)
   (((string? s1) (string? s2) (integer? start1)) boolean?)
   (((string? s1) (string? s2) (integer? start1) (integer? end1)) boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2))
    boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2)
     (integer? end2))
    boolean?))
  (tags pure))
 ((name . "string>")
  (signature
   case-lambda
   (((string? s1) (string? s2)) boolean?)
   (((string? s1) (string? s2) (integer? start1)) boolean?)
   (((string? s1) (string? s2) (integer? start1) (integer? end1)) boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2))
    boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2)
     (integer? end2))
    boolean?))
  (tags pure))
 ((name . "string<=")
  (signature
   case-lambda
   (((string? s1) (string? s2)) boolean?)
   (((string? s1) (string? s2) (integer? start1)) boolean?)
   (((string? s1) (string? s2) (integer? start1) (integer? end1)) boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2))
    boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2)
     (integer? end2))
    boolean?))
  (tags pure))
 ((name . "string>=")
  (signature
   case-lambda
   (((string? s1) (string? s2)) boolean?)
   (((string? s1) (string? s2) (integer? start1)) boolean?)
   (((string? s1) (string? s2) (integer? start1) (integer? end1)) boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2))
    boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2)
     (integer? end2))
    boolean?))
  (tags pure))
 ((name . "string-ci=")
  (signature
   case-lambda
   (((string? s1) (string? s2)) boolean?)
   (((string? s1) (string? s2) (integer? start1)) boolean?)
   (((string? s1) (string? s2) (integer? start1) (integer? end1)) boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2))
    boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2)
     (integer? end2))
    boolean?))
  (tags pure))
 ((name . "string-ci<>")
  (signature
   case-lambda
   (((string? s1) (string? s2)) boolean?)
   (((string? s1) (string? s2) (integer? start1)) boolean?)
   (((string? s1) (string? s2) (integer? start1) (integer? end1)) boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2))
    boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2)
     (integer? end2))
    boolean?))
  (tags pure))
 ((name . "string-ci<")
  (signature
   case-lambda
   (((string? s1) (string? s2)) boolean?)
   (((string? s1) (string? s2) (integer? start1)) boolean?)
   (((string? s1) (string? s2) (integer? start1) (integer? end1)) boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2))
    boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2)
     (integer? end2))
    boolean?))
  (tags pure))
 ((name . "string-ci>")
  (signature
   case-lambda
   (((string? s1) (string? s2)) boolean?)
   (((string? s1) (string? s2) (integer? start1)) boolean?)
   (((string? s1) (string? s2) (integer? start1) (integer? end1)) boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2))
    boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2)
     (integer? end2))
    boolean?))
  (tags pure))
 ((name . "string-ci<=")
  (signature
   case-lambda
   (((string? s1) (string? s2)) boolean?)
   (((string? s1) (string? s2) (integer? start1)) boolean?)
   (((string? s1) (string? s2) (integer? start1) (integer? end1)) boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2))
    boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2)
     (integer? end2))
    boolean?))
  (tags pure))
 ((name . "string-ci>=")
  (signature
   case-lambda
   (((string? s1) (string? s2)) boolean?)
   (((string? s1) (string? s2) (integer? start1)) boolean?)
   (((string? s1) (string? s2) (integer? start1) (integer? end1)) boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2))
    boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2)
     (integer? end2))
    boolean?))
  (tags pure))
 ((name . "string-hash")
  (signature
   case-lambda
   (((string? s)) integer?)
   (((string? s) (integer? bound)) integer?)
   (((string? s) (integer? bound) (integer? start)) integer?)
   (((string? s) (integer? bound) (integer? start) (integer? end)) integer?))
  (tags pure))
 ((name . "string-hash-ci")
  (signature
   case-lambda
   (((string? s)) integer?)
   (((string? s) (integer? bound)) integer?)
   (((string? s) (integer? bound) (integer? start)) integer?)
   (((string? s) (integer? bound) (integer? start) (integer? end)) integer?))
  (tags pure))
 ((name . "string-prefix-length")
  (signature
   case-lambda
   (((string? s1) (string? s2)) integer?)
   (((string? s1) (string? s2) (integer? start1)) integer?)
   (((string? s1) (string? s2) (integer? start1) (integer? end1)) integer?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2))
    integer?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2)
     (integer? end2))
    integer?))
  (tags pure))
 ((name . "string-suffix-length")
  (signature
   case-lambda
   (((string? s1) (string? s2)) integer?)
   (((string? s1) (string? s2) (integer? start1)) integer?)
   (((string? s1) (string? s2) (integer? start1) (integer? end1)) integer?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2))
    integer?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2)
     (integer? end2))
    integer?))
  (tags pure))
 ((name . "string-prefix-length-ci")
  (signature
   case-lambda
   (((string? s1) (string? s2)) integer?)
   (((string? s1) (string? s2) (integer? start1)) integer?)
   (((string? s1) (string? s2) (integer? start1) (integer? end1)) integer?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2))
    integer?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2)
     (integer? end2))
    integer?))
  (tags pure))
 ((name . "string-suffix-length-ci")
  (signature
   case-lambda
   (((string? s1) (string? s2)) integer?)
   (((string? s1) (string? s2) (integer? start1)) integer?)
   (((string? s1) (string? s2) (integer? start1) (integer? end1)) integer?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2))
    integer?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2)
     (integer? end2))
    integer?))
  (tags pure))
 ((name . "string-prefix?")
  (signature
   case-lambda
   (((string? s1) (string? s2)) boolean?)
   (((string? s1) (string? s2) (integer? start1)) boolean?)
   (((string? s1) (string? s2) (integer? start1) (integer? end1)) boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2))
    boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2)
     (integer? end2))
    boolean?))
  (tags pure))
 ((name . "string-suffix?")
  (signature
   case-lambda
   (((string? s1) (string? s2)) boolean?)
   (((string? s1) (string? s2) (integer? start1)) boolean?)
   (((string? s1) (string? s2) (integer? start1) (integer? end1)) boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2))
    boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2)
     (integer? end2))
    boolean?))
  (tags pure))
 ((name . "string-prefix-ci?")
  (signature
   case-lambda
   (((string? s1) (string? s2)) boolean?)
   (((string? s1) (string? s2) (integer? start1)) boolean?)
   (((string? s1) (string? s2) (integer? start1) (integer? end1)) boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2))
    boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2)
     (integer? end2))
    boolean?))
  (tags pure))
 ((name . "string-suffix-ci?")
  (signature
   case-lambda
   (((string? s1) (string? s2)) boolean?)
   (((string? s1) (string? s2) (integer? start1)) boolean?)
   (((string? s1) (string? s2) (integer? start1) (integer? end1)) boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2))
    boolean?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2)
     (integer? end2))
    boolean?))
  (tags pure))
 ((name . "string-index")
  (signature
   case-lambda
   ((((or char? char-set? procedure?) c) (string? s)) (or integer? #f))
   ((((or char? char-set? procedure?) c) (string? s) (integer? start))
    (or integer? #f))
   ((((or char? char-set? procedure?) c)
     (string? s)
     (integer? start)
     (integer? end))
    (or integer? #f)))
  (subsigs (c (lambda ((char? char)) *)))
  (tags pure))
 ((name . "string-index-right")
  (signature
   case-lambda
   ((((or char? char-set? procedure?) c) (string? s)) (or integer? #f))
   ((((or char? char-set? procedure?) c) (string? s) (integer? start))
    (or integer? #f))
   ((((or char? char-set? procedure?) c)
     (string? s)
     (integer? start)
     (integer? end))
    (or integer? #f)))
  (subsigs (c (lambda ((char? char)) *)))
  (tags pure))
 ((name . "string-skip")
  (signature
   case-lambda
   ((((or char? char-set? procedure?) c) (string? s)) (or integer? #f))
   ((((or char? char-set? procedure?) c) (string? s) (integer? start))
    (or integer? #f))
   ((((or char? char-set? procedure?) c)
     (string? s)
     (integer? start)
     (integer? end))
    (or integer? #f)))
  (subsigs (c (lambda ((char? char)) *)))
  (tags pure))
 ((name . "string-skip-right")
  (signature
   case-lambda
   ((((or char? char-set? procedure?) c) (string? s)) (or integer? #f))
   ((((or char? char-set? procedure?) c) (string? s) (integer? start))
    (or integer? #f))
   ((((or char? char-set? procedure?) c)
     (string? s)
     (integer? start)
     (integer? end))
    (or integer? #f)))
  (subsigs (c (lambda ((char? char)) *)))
  (tags pure))
 ((name . "string-count")
  (signature
   case-lambda
   ((((or char? char-set? procedure?) c) (string? s)) integer?)
   ((((or char? char-set? procedure?) c) (string? s) (integer? start)) integer?)
   ((((or char? char-set? procedure?) c)
     (string? s)
     (integer? start)
     (integer? end))
    integer?))
  (subsigs (c (lambda ((char? char)) *)))
  (tags pure))
 ((name . "string-contains")
  (signature
   case-lambda
   (((string? s1) (string? s2)) (or integer? #f))
   (((string? s1) (string? s2) (integer? start1)) (or integer? #f))
   (((string? s1) (string? s2) (integer? start1) (integer? end1))
    (or integer? #f))
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2))
    (or integer? #f))
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2)
     (integer? end2))
    (or integer? #f)))
  (tags pure))
 ((name . "string-contains-ci")
  (signature
   case-lambda
   (((string? s1) (string? s2)) (or integer? #f))
   (((string? s1) (string? s2) (integer? start1)) (or integer? #f))
   (((string? s1) (string? s2) (integer? start1) (integer? end1))
    (or integer? #f))
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2))
    (or integer? #f))
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2)
     (integer? end2))
    (or integer? #f)))
  (tags pure))
 ((name . "string-titlecase")
  (signature
   case-lambda
   (((string? s)) string?)
   (((string? s) (integer? start)) string?)
   (((string? s) (integer? start) (integer? end)) string?))
  (tags pure))
 ((name . "string-titlecase!")
  (signature
   case-lambda
   (((string? s)) undefined)
   (((string? s) (integer? start)) undefined)
   (((string? s) (integer? start) (integer? end)) undefined)))
 ((name . "string-upcase")
  (signature
   case-lambda
   (((string? s)) string?)
   (((string? s) (integer? start)) string?)
   (((string? s) (integer? start) (integer? end)) string?))
  (tags pure))
 ((name . "string-upcase!")
  (signature
   case-lambda
   (((string? s)) undefined)
   (((string? s) (integer? start)) undefined)
   (((string? s) (integer? start) (integer? end)) undefined)))
 ((name . "string-downcase")
  (signature
   case-lambda
   (((string? s)) string?)
   (((string? s) (integer? start)) string?)
   (((string? s) (integer? start) (integer? end)) string?))
  (tags pure))
 ((name . "string-downcase!")
  (signature
   case-lambda
   (((string? s)) undefined)
   (((string? s) (integer? start)) undefined)
   (((string? s) (integer? start) (integer? end)) undefined)))
 ((name . "string-reverse")
  (signature
   case-lambda
   (((string? s)) string?)
   (((string? s) (integer? start)) string?)
   (((string? s) (integer? start) (integer? end)) string?))
  (tags pure))
 ((name . "string-reverse!")
  (signature
   case-lambda
   (((string? s)) undefined)
   (((string? s) (integer? start)) undefined)
   (((string? s) (integer? start) (integer? end)) undefined)))
 ((name . "string-append")
  (signature lambda ((string? string) ...) string?)
  (tags pure))
 ((name . "string-concatenate")
  (signature lambda ((list? string-list)) string?)
  (tags pure))
 ((name . "string-append/shared")
  (signature lambda ((string? string) ...) string?)
  (tags pure))
 ((name . "string-concatenate/shared")
  (signature lambda ((list? string-list)) string?)
  (tags pure))
 ((name . "string-concatenate-reverse")
  (signature
   case-lambda
   (((list? string-list)) string?)
   (((list? string-list) (string? final-string)) string?)
   (((list? string-list) (string? final-string) (integer? end)) string?))
  (tags pure))
 ((name . "string-concatenate-reverse/shared")
  (signature
   case-lambda
   (((list? string-list)) string?)
   (((list? string-list) (string? final-string)) string?)
   (((list? string-list) (string? final-string) (integer? end)) string?))
  (tags pure))
 ((name . "string-map")
  (signature
   case-lambda
   (((procedure? proc) (string? s)) string?)
   (((procedure? proc) (string? s) (integer? start)) string?)
   (((procedure? proc) (string? s) (integer? start) (integer? end)) string?))
  (subsigs (proc (lambda ((char? c) ...) char?)))
  (tags pure))
 ((name . "string-map!")
  (signature
   case-lambda
   (((procedure? proc) (string? s)) undefined)
   (((procedure? proc) (string? s) (integer? start)) undefined)
   (((procedure? proc) (string? s) (integer? start) (integer? end)) undefined))
  (subsigs (proc (lambda ((char? c) ...) char?))))
 ((name . "string-fold")
  (signature
   case-lambda
   (((procedure? kons) knil (string? s)) *)
   (((procedure? kons) knil (string? s) (integer? start)) *)
   (((procedure? kons) knil (string? s) (integer? start) (integer? end)) *))
  (subsigs (kons (lambda ((char? c) state) *)))
  (tags pure))
 ((name . "string-fold-right")
  (signature
   case-lambda
   (((procedure? kons) knil (string? s)) *)
   (((procedure? kons) knil (string? s) (integer? start)) *)
   (((procedure? kons) knil (string? s) (integer? start) (integer? end)) *))
  (subsigs (kons (lambda ((char? c) state) *)))
  (tags pure))
 ((name . "string-unfold")
  (signature
   case-lambda
   (((procedure? p) (procedure? f) (procedure? g) seed) string?)
   (((procedure? p) (procedure? f) (procedure? g) seed (string? base)) string?)
   (((procedure? p)
     (procedure? f)
     (procedure? g)
     seed
     (string? base)
     (procedure? make-final))
    string?))
  (subsigs
   (p (lambda (seed) boolean?))
   (f (lambda (seed) *))
   (g (lambda (seed) *))
   (make-final (lambda (seed) string?)))
  (tags pure))
 ((name . "string-unfold-right")
  (signature
   case-lambda
   (((procedure? p) (procedure? f) (procedure? g) seed) string?)
   (((procedure? p) (procedure? f) (procedure? g) seed (string? base)) string?)
   (((procedure? p)
     (procedure? f)
     (procedure? g)
     seed
     (string? base)
     (procedure? make-final))
    string?))
  (subsigs
   (p (lambda (seed) boolean?))
   (f (lambda (seed) *))
   (g (lambda (seed) *))
   (make-final (lambda (seed) string?)))
  (tags pure))
 ((name . "string-for-each")
  (signature
   case-lambda
   (((procedure? proc) (string? s)) undefined)
   (((procedure? proc) (string? s) (integer? start)) undefined)
   (((procedure? proc) (string? s) (integer? start) (integer? end)) undefined))
  (subsigs (proc (lambda ((char? c)) undefined))))
 ((name . "string-for-each-index")
  (signature
   case-lambda
   (((procedure? proc) (string? s)) undefined)
   (((procedure? proc) (string? s) (integer? start)) undefined)
   (((procedure? proc) (string? s) (integer? start) (integer? end)) undefined))
  (subsigs (proc (lambda ((integer? index)) undefined))))
 ((name . "xsubstring")
  (signature
   case-lambda
   (((string? s) (integer? from)) string?)
   (((string? s) (integer? from) (integer? to)) string?)
   (((string? s) (integer? from) (integer? to) (integer? start)) string?)
   (((string? s) (integer? from) (integer? to) (integer? start) (integer? end))
    string?))
  (tags pure))
 ((name . "string-xcopy!")
  (signature
   case-lambda
   (((string? target) (integer? tstart) (string? s) (integer? sfrom))
    undefined)
   (((string? target)
     (integer? tstart)
     (string? s)
     (integer? sfrom)
     (integer? sto))
    undefined)
   (((string? target)
     (integer? tstart)
     (string? s)
     (integer? sfrom)
     (integer? sto)
     (integer? start))
    undefined)
   (((string? target)
     (integer? tstart)
     (string? s)
     (integer? sfrom)
     (integer? sto)
     (integer? start)
     (integer? end))
    undefined)))
 ((name . "string-replace")
  (signature
   case-lambda
   (((string? s1) (string? s2) (integer? start1) (integer? end1)) string?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2))
    string?)
   (((string? s1)
     (string? s2)
     (integer? start1)
     (integer? end1)
     (integer? start2)
     (integer? end2))
    string?))
  (tags pure))
 ((name . "string-tokenize")
  (signature
   case-lambda
   (((string? s)) list?)
   (((string? s) (char-set? token-set)) list?)
   (((string? s) (char-set? token-set) (integer? start)) list?)
   (((string? s) (char-set? token-set) (integer? start) (integer? end)) list?))
  (tags pure))
 ((name . "string-filter")
  (signature
   case-lambda
   ((((or char? char-set? procedure?) c) (string? s)) string?)
   ((((or char? char-set? procedure?) c) (string? s) (integer? start)) string?)
   ((((or char? char-set? procedure?) c)
     (string? s)
     (integer? start)
     (integer? end))
    string?))
  (subsigs (c (lambda ((char? char)) *)))
  (tags pure))
 ((name . "string-delete")
  (signature
   case-lambda
   ((((or char? char-set? procedure?) c) (string? s)) string?)
   ((((or char? char-set? procedure?) c) (string? s) (integer? start)) string?)
   ((((or char? char-set? procedure?) c)
     (string? s)
     (integer? start)
     (integer? end))
    string?))
  (subsigs (c (lambda ((char? char)) *)))
  (tags pure))
 ((name . "string-parse-start+end")
  (signature
   lambda
   ((procedure? proc) (string? s) (list? args))
   (values list? integer? integer?))
  (tags pure))
 ((name . "string-parse-final-start+end")
  (signature
   lambda
   ((procedure? proc) (string? s) (list? args))
   (values integer? integer?))
  (tags pure))
 ((name . "let-string-start+end")
  (signature
   syntax-rules
   ()
   ((_ (start end) proc s args body ...))
   ((_ (rest start end) proc s args body ...)))
  (subsigs (proc (value procedure?)) (s (value string?)) (args (value list?))))
 ((name . "check-substring-spec")
  (signature
   lambda
   ((procedure? proc) (string? s) (integer? start) (integer? end))
   undefined))
 ((name . "substring-spec-ok?")
  (signature lambda ((string? s) (integer? start) (integer? end)) boolean?)
  (tags pure))
 ((name . "make-kmp-restart-vector")
  (signature
   case-lambda
   (((string? s)) vector?)
   (((string? s) (procedure? c=)) vector?)
   (((string? s) (procedure? c=) (integer? start)) vector?)
   (((string? s) (procedure? c=) (integer? start) (integer? end)) vector?))
  (subsigs (c= (lambda ((char? a) (char? b)) boolean?)))
  (tags pure))
 ((name . "kmp-step")
  (signature
   lambda
   ((string? pat)
    (vector? rv)
    (char? c)
    (integer? i)
    (procedure? c=)
    (integer? p-start))
   integer?)
  (subsigs (c= (lambda ((char? a) (char? b)) boolean?)))
  (tags pure))
 ((name . "string-kmp-partial-search")
  (signature
   case-lambda
   (((string? pat) (vector? rv) (string? s) (integer? i)) integer?)
   (((string? pat) (vector? rv) (string? s) (integer? i) (procedure? c=))
    integer?)
   (((string? pat)
     (vector? rv)
     (string? s)
     (integer? i)
     (procedure? c=)
     (integer? p-start))
    integer?)
   (((string? pat)
     (vector? rv)
     (string? s)
     (integer? i)
     (procedure? c=)
     (integer? p-start)
     (integer? s-start))
    integer?)
   (((string? pat)
     (vector? rv)
     (string? s)
     (integer? i)
     (procedure? c=)
     (integer? p-start)
     (integer? s-start)
     (integer? s-end))
    integer?))
  (subsigs (c= (lambda ((char? a) (char? b)) boolean?)))
  (tags pure)))
