(((name . "s8vector?") (signature lambda (obj) boolean?) (tags pure predicate))
 ((name . "make-s8vector")
  (signature
   case-lambda
   (((integer? size)) s8vector?)
   (((integer? size) (integer? fill)) s8vector?))
  (tags pure))
 ((name . "s8vector-length")
  (signature lambda ((s8vector? vec)) integer?)
  (tags pure))
 ((name . "s8vector-ref")
  (signature lambda ((s8vector? vec) (integer? i)) integer?)
  (tags pure))
 ((name . "s8vector-set!")
  (signature lambda ((s8vector? vec) (integer? i) (integer? value)) undefined))
 ((name . "s8vector->list")
  (signature lambda ((s8vector? vec)) list?)
  (tags pure))
 ((name . "list->s8vector")
  (signature lambda ((list? proper-list)) s8vector?)
  (tags pure)))
