(((name . delay)
  (signature syntax-rules ()
             ((_ expression) promise?)))
 ((name . lazy)
  (signature syntax-rules ()
             ((_ expression) promise?))
  (syntax-param-signatures (expression promise?)))
 ((name . force)
  (signature lambda ((promise? expression)) *))
 ((name . eager)
  (signature lambda ((expression)) promise?)))
