(

 ((name . s16vector?)
  (signature lambda (obj) boolean?)
  (tags pure predicate))
 ((name . make-s16vector)
  (signature lambda ((integer? size)) s16vector?))
 ((name . make-s16vector)
  (signature lambda ((integer? size) (integer? fill)) s16vector?)
  (tags pure))
 ((name . s16vector-length)
  (signature lambda ((s16vector? vec)) integer?)
  (tags pure))
 ((name . s16vector-ref)
  (signature lambda ((s16vector? vec) (integer? i)) integer?)
  (tags pure))
 ((name . s16vector-set!)
  (signature lambda ((s16vector? vec) (integer? i) (integer? value)) undefined))
 ((name . s16vector->list)
  (signature lambda ((s16vector? vec)) list?)
  (tags pure))
 ((name . list->s16vector)
  (signature lambda ((list? proper-list)) s16vector?)
  (tags pure))

)
