(((name . "s32vector?")
  (signature lambda (obj) boolean?)
  (tags pure predicate)
  (desc . "Returns #t if the if an object is homogenous s32vector, #f otherwise."))
 ((name . "make-s32vector")
  (signature
   case-lambda
   (((integer? size)) s32vector?)
   (((integer? size) (integer? fill)) s32vector?))
  (tags pure)
  (desc . "Create homogenous s32 vector. If fill is given, it must be signed exact integer in the range -(2^31) to (2^31)-1. If fill isn't given, vector is filled with unspecified values which are guaranteed to fit into the range of the s32vector."))
 ((name . "s32vector")
  (signature lambda ((integer? value) ...) s32vector?)
  (tags pure)
  (desc . "Create homogenous s32 vector. Each value must be signed exact integer in the range -(2^31) to (2^31)-1."))
 ((name . "s32vector-length")
  (signature lambda ((s32vector? vec)) integer?)
  (tags pure)
  (desc . "Returns the number of elements in s32vector as an exact integer."))
 ((name . "s32vector-ref")
  (signature lambda ((s32vector? vec) (integer? i)) integer?)
  (tags pure)
  (desc . "Returns i-th element in the vector. i must be in range [0, (s32vector-length vec))"))
 ((name . "s32vector-set!")
  (signature lambda ((s32vector? vec) (integer? i) (integer? value)) undefined)
  (desc . "s32vector-set! stores value in element k of vector. Value must be signed exact integer in the range -(2^31) to (2^31)-1. i must be in range [0, (s32vector-length vec))"))
 ((name . "s32vector->list")
  (signature lambda ((s32vector? vec)) list?)
  (tags pure)
  (desc . "Converts a homogenous vector to a list."))
 ((name . "list->s32vector")
  (signature lambda ((list? proper-list)) s32vector?)
  (subsigs
    (proper-list (list integer?)))
  (tags pure)
  (desc . "Converts a list to a homogenous s32vector. Each element in input list must be signed exact integer in the range -(2^31) to (2^31)-1.")))
