(((name . "s64vector?")
  (signature lambda (obj) boolean?)
  (tags pure predicate))
 ((name . "make-s64vector")
  (signature
   case-lambda
   (((integer? size)) s64vector?)
   (((integer? size) (integer? fill)) s64vector?))
  (tags pure))
 ((name . "s64vector-length")
  (signature lambda ((s64vector? vec)) integer?)
  (tags pure))
 ((name . "s64vector-ref")
  (signature lambda ((s64vector? vec) (integer? i)) integer?)
  (tags pure))
 ((name . "s64vector-set!")
  (signature
   lambda
   ((s64vector? vec) (integer? i) (integer? value))
   undefined))
 ((name . "s64vector->list")
  (signature lambda ((s64vector? vec)) list?)
  (tags pure))
 ((name . "list->s64vector")
  (signature lambda ((list? proper-list)) s64vector?)
  (tags pure)))
