(((name . "program-vicinity") (signature lambda () vicinity) (tags pure))
 ((name . "library-vicinity") (signature lambda () vicinity) (tags pure))
 ((name . "implementation-vicinity")
  (signature lambda () vicinity)
  (tags pure))
 ((name . "user-vicinity") (signature lambda () vicinity) (tags pure))
 ((name . "home-vicinity") (signature lambda () vicinity) (tags pure))
 ((name . "in-vicinity")
  (signature lambda ((vicinity vicinity) (string? filename)) string?)
  (tags pure))
 ((name . "sub-vicinity")
  (signature lambda ((vicinity vicinity) (string? name)) vicinity)
  (tags pure))
 ((name . "make-vicinity")
  (signature lambda ((string? dir-path)) vicinity)
  (tags pure))
 ((name . "pathname->vicinity")
  (signature lambda ((string? path)) vicinity)
  (tags pure))
 ((name . "vicinity:suffix?")
  (signature lambda ((char? chr)) boolean?)
  (tags pure)))
