(((name . make-list-queue)
  (signature lambda ((list? list)) list-queue?)
  (tags pure))
 ((name . make-list-queue)
  (signature lambda ((list? list) (pair? last)) list-queue?)
  (tags pure))
 ((name . list-queue) (signature lambda (element ...) list-queue?) (tags pure))
 ((name . list-queue)
  (signature lambda ((list-queue? list-queue)) list-queue?)
  (tags pure))
 ((name . list-queue-unfold)
  (signature
   lambda
   ((procedure? stop?) (procedure? mapper) (procedure? successor) seed)
   list-queue?)
  (tags pure)
  (subsigs
   (stop? (lambda (seed) boolean?))
   (mapper (lambda (seed) *))
   (successor (lambda (seed) *))))
 ((name . list-queue-unfold)
  (signature
   lambda
   ((procedure? stop?)
    (procedure? mapper)
    (procedure? successor)
    seed
    (list-queue? queue))
   list-queue?)
  (tags pure)
  (subsigs
   (stop? (lambda (seed) boolean?))
   (mapper (lambda (seed) *))
   (successor (lambda (seed) *))))
 ((name . list-queue-unfold-right)
  (signature
   lambda
   ((procedure? stop?) (procedure? mapper) (procedure? successor) seed)
   list-queue?)
  (tags pure)
  (subsigs
   (stop? (lambda (seed) boolean?))
   (mapper (lambda (seed) *))
   (successor (lambda (seed) *))))
 ((name . list-queue-unfold-right)
  (signature
   lambda
   ((procedure? stop?)
    (procedure? mapper)
    (procedure? successor)
    seed
    (list-queue? queue))
   list-queue?)
  (tags pure)
  (subsigs
   (stop? (lambda (seed) boolean?))
   (mapper (lambda (seed) *))
   (successor (lambda (seed) *))))
 ((name . list-queue?) (signature lambda (obj) boolean?) (tags pure predicate))
 ((name . list-queue-empty?)
  (signature lambda ((list-queue? list-queue)) boolean?)
  (tags pure))
 ((name . list-queue-front)
  (signature lambda ((list-queue? list-queue)) *)
  (tags pure))
 ((name . list-queue-back)
  (signature lambda ((list-queue? list-queue)) *)
  (tags pure))
 ((name . list-queue-list)
  (signature lambda ((list-queue? list-queue)) list?)
  (tags pure))
 ((name . list-queue-first-last)
  (signature lambda ((list-queue? list-queue)) (values list? list?))
  (tags pure))
 ((name . list-queue-add-front!)
  (signature lambda ((list-queue? list-queue) element) undefined))
 ((name . list-queue-add-back!)
  (signature lambda ((list-queue? list-queue) element) undefined))
 ((name . list-queue-remove-front!)
  (signature lambda ((list-queue? list-queue)) *))
 ((name . list-queue-remove-back!)
  (signature lambda ((list-queue? list-queue)) *))
 ((name . list-queue-remove-all!)
  (signature lambda ((list-queue? list-queue)) list?))
 ((name . list-queue-set-list!)
  (signature lambda ((list-queue? list-queue) (list? list)) undefined))
 ((name . list-queue-set-list!)
  (signature
   lambda
   ((list-queue? list-queue) (list? list) (pair? last))
   undefined))
 ((name . list-queue-append)
  (signature lambda ((list-queue? list-queue) ...) list-queue?)
  (tags pure))
 ((name . list-queue-append!)
  (signature lambda ((list-queue? list-queue) ...) list-queue?))
 ((name . list-queue-concatenate)
  (signature lambda ((list? list-of-list-queues)) list-queue?)
  (tags pure))
 ((name . list-queue-map)
  (signature lambda ((procedure? proc) (list-queue? list-queue)) list-queue?)
  (tags pure)
  (subsigs (proc (lambda (element) *))))
 ((name . list-queue-map!)
  (signature lambda ((procedure? proc) (list-queue? list-queue)) undefined)
  (subsigs (proc (lambda (element) *))))
 ((name . list-queue-for-each)
  (signature lambda ((procedure? proc) (list-queue? list-queue)) undefined)
  (subsigs (proc (lambda (element) undefined)))))
