(((name . "make-rtd")
  (signature
   case-lambda
   (((symbol? name) (vector? fieldspecs)) rtd?)
   (((symbol? name) (vector? fieldspecs) ((or rtd? #f) parent)) rtd?))
  (tags pure))
 ((name . "rtd?") (signature lambda (obj) boolean?) (tags pure predicate))
 ((name . "rtd-constructor")
  (signature
   case-lambda
   (((rtd? rtd)) procedure?)
   (((rtd? rtd) (vector? fieldspec)) procedure?))
  (subsigs (return (lambda (fieldvalue ...) record?)))
  (tags pure))
 ((name . "rtd-predicate")
  (signature lambda ((rtd? rtd)) procedure?)
  (subsigs (return (lambda (obj) boolean?)))
  (tags pure))
 ((name . "rtd-accessor")
  (signature lambda ((rtd? rtd) (symbol? field)) procedure?)
  (subsigs (return (lambda ((record? rec)) *)))
  (tags pure))
 ((name . "rtd-mutator")
  (signature lambda ((rtd? rtd) (symbol? field)) procedure?)
  (subsigs (return (lambda ((record? rec) value) undefined)))
  (tags pure)))
