(((name . "s16vector?")
  (signature lambda (obj) boolean?)
  (tags pure predicate)
  (desc . "Returns #t if the if an object is homogenous s16vector, #f otherwise."))
 ((name . "make-s16vector")
  (signature
   case-lambda
   (((integer? size)) s16vector?)
   (((integer? size) (integer? fill)) s16vector?))
  (tags pure)
  (desc . "Create homogenous s16 vector. If fill is given, it must be signed exact integer in the range -(2^15) to (2^15)-1. If fill isn't given, vector is filled with unspecified values which are guaranteed to fit into the range of the s16vector."))
 ((name . "s16vector")
  (signature lambda ((integer? value) ...) s16vector?)
  (tags pure)
  (desc . "Create homogenous s16 vector. Each value must be signed exact integer in the range -(2^15) to (2^15)-1."))
 ((name . "s16vector-length")
  (signature lambda ((s16vector? vec)) integer?)
  (tags pure)
  (desc . "Returns the number of elements in s16vector as an exact integer."))
 ((name . "s16vector-ref")
  (signature lambda ((s16vector? vec) (integer? i)) integer?)
  (tags pure)
  (desc . "Returns i-th element in the vector. i must be in range [0, (s16vector-length vec))"))
 ((name . "s16vector-set!")
  (signature lambda ((s16vector? vec) (integer? i) (integer? value)) undefined)
  (desc . "s16vector-set! stores value in element k of vector. Value must be signed exact integer in the range -(2^15) to (2^15)-1. i must be in range [0, (s16vector-length vec))"))
 ((name . "s16vector->list")
  (signature lambda ((s16vector? vec)) list?)
  (tags pure)
  (desc . "Converts a homogenous vector to a list."))
 ((name . "list->s16vector")
  (signature lambda ((list? proper-list)) s16vector?)
  (subsigs
    (proper-list (list integer?)))
  (tags pure)
  (desc . "Converts a list to a homogenous s16vector. Each element in input list must be signed exact integer in the range -(2^15) to (2^15)-1.")))
