(((name . "make-parameter") (signature lambda (obj) procedure?) (tags pure))
 ((name . "make-parameter")
  (signature lambda (obj (procedure? converter)) procedure?)
  (subsigs (converter (lambda (obj) *)))
  (tags pure))
 ((name . "parameterize")
  (signature syntax-rules () ((_ ((param1 value1) ...) body)))))
