(((name . "floor/")
  (signature
   lambda
   ((integer? numerator) (integer? denominator))
   (values integer? integer?))
  (tags pure))
 ((name . "floor-quotient")
  (signature lambda ((integer? numerator) (integer? denominator)) integer?)
  (tags pure))
 ((name . "floor-remainder")
  (signature lambda ((integer? numerator) (integer? denominator)) integer?)
  (tags pure))
 ((name . "ceiling/")
  (signature
   lambda
   ((integer? numerator) (integer? denominator))
   (values integer? integer?))
  (tags pure))
 ((name . "ceiling-quotient")
  (signature lambda ((integer? numerator) (integer? denominator)) integer?)
  (tags pure))
 ((name . "ceiling-remainder")
  (signature lambda ((integer? numerator) (integer? denominator)) integer?)
  (tags pure))
 ((name . "truncate/")
  (signature
   lambda
   ((integer? numerator) (integer? denominator))
   (values integer? integer?))
  (tags pure))
 ((name . "truncate-quotient")
  (signature lambda ((integer? numerator) (integer? denominator)) integer?)
  (tags pure))
 ((name . "truncate-remainder")
  (signature lambda ((integer? numerator) (integer? denominator)) integer?)
  (tags pure))
 ((name . "round/")
  (signature
   lambda
   ((integer? numerator) (integer? denominator))
   (values integer? integer?))
  (tags pure))
 ((name . "round-quotient")
  (signature lambda ((integer? numerator) (integer? denominator)) integer?)
  (tags pure))
 ((name . "round-remainder")
  (signature lambda ((integer? numerator) (integer? denominator)) integer?)
  (tags pure))
 ((name . "euclidean/")
  (signature
   lambda
   ((integer? numerator) (integer? denominator))
   (values integer? integer?))
  (tags pure))
 ((name . "euclidean-quotient")
  (signature lambda ((integer? numerator) (integer? denominator)) integer?)
  (tags pure))
 ((name . "euclidean-remainder")
  (signature lambda ((integer? numerator) (integer? denominator)) integer?)
  (tags pure))
 ((name . "balanced/")
  (signature
   lambda
   ((integer? numerator) (integer? denominator))
   (values integer? integer?))
  (tags pure))
 ((name . "balanced-quotient")
  (signature lambda ((integer? numerator) (integer? denominator)) integer?)
  (tags pure))
 ((name . "balanced-remainder")
  (signature lambda ((integer? numerator) (integer? denominator)) integer?)
  (tags pure)))
