(((name . write-with-shared-structure)
  (signature lambda (obj) undefined)
  (parameterized-by "(scheme base) current-output-port"))
 ((name . write-with-shared-structure)
  (signature lambda (obj (output-port? port)) undefined))
 ((name . write-with-shared-structure)
  (signature lambda (obj (output-port? port) optarg) undefined)))
