(((name . current-language)
  (signature lambda () symbol?)
  (tags pure))
 ((name . current-language)
  (signature lambda ((symbol? lang)) undefined))
 ((name . current-country)
  (signature lambda () symbol?)
  (tags pure))
 ((name . current-country)
  (signature lambda ((symbol? country)) undefined))
 ((name . current-locale-details)
  (signature lambda () list?)
  (tags pure))
 ((name . current-locale-details)
  (signature lambda ((list? symbols)) undefined))
 ((name . declare-bundle!)
  (signature lambda ((list? bundle-specifier) (list? alist)) undefined))
 ((name . store-bundle)
  (signature lambda ((list? bundle-specifier)) boolean?))
 ((name . load-bundle!)
  (signature lambda ((list? bundle-specifier)) boolean?))
 ((name . localized-template)
  (signature lambda ((symbol? package-name) (symbol? message-tpl-name)) (or string? #f))))
