(((name . "u16vector?")
  (signature lambda (obj) boolean?)
  (tags pure predicate)
  (desc . "Returns #t if the if an object is homogenous u16vector, #f otherwise."))
 ((name . "make-u16vector")
  (signature
   case-lambda
   (((integer? size)) u16vector?)
   (((integer? size) (integer? fill)) u16vector?))
  (tags pure)
  (desc . "Create homogenous u16 vector. If fill is given, it must be unsigned exact integer in the range 0 to (2^16)-1. If fill isn't given, vector is filled with unspecified values which are guaranteed to fit into the range of the u16vector."))
 ((name . "u16vector")
  (signature lambda ((integer? value) ...) u16vector?)
  (tags pure)
  (desc . "Create homogenous u16 vector. Each value must be unsigned exact integer in the range 0 to (2^16)-1."))
 ((name . "u16vector-length")
  (signature lambda ((u16vector? vec)) integer?)
  (tags pure)
  (desc . "Returns the number of elements in u16vector as an exact integer."))
 ((name . "u16vector-ref")
  (signature lambda ((u16vector? vec) (integer? i)) integer?)
  (tags pure)
  (desc . "Returns i-th element in the vector. i must be in range [0, (u16vector-length vec))"))
 ((name . "u16vector-set!")
  (signature lambda ((u16vector? vec) (integer? i) (integer? value)) undefined)
  (desc . "u16vector-set! stores value in element k of vector. Value must be unsigned exact integer in the range 0 to (2^16)-1. i must be in range [0, (u16vector-length vec))"))
 ((name . "u16vector->list")
  (signature lambda ((u16vector? vec)) list?)
  (tags pure)
  (desc . "Converts a homogenous vector to a list."))
 ((name . "list->u16vector")
  (signature lambda ((list? proper-list)) u16vector?)
  (subsigs
    (proper-list (list integer?)))
  (tags pure)
  (desc . "Converts a list to a homogenous u16vector. Each element in input list must be unsigned exact integer in the range 0 to (2^16)-1.")))
