(((name . "u8vector?") (signature lambda (obj) boolean?) (tags pure predicate))
 ((name . "make-u8vector") (signature lambda ((integer? size)) u8vector?))
 ((name . "make-u8vector")
  (signature lambda ((integer? size) (integer? fill)) u8vector?)
  (tags pure))
 ((name . "u8vector-length")
  (signature lambda ((u8vector? vec)) integer?)
  (tags pure))
 ((name . "u8vector-ref")
  (signature lambda ((u8vector? vec) (integer? i)) integer?)
  (tags pure))
 ((name . "u8vector-set!")
  (signature lambda ((u8vector? vec) (integer? i) (integer? value)) undefined))
 ((name . "u8vector->list")
  (signature lambda ((u8vector? vec)) list?)
  (tags pure))
 ((name . "list->u8vector")
  (signature lambda ((list? proper-list)) u8vector?)
  (tags pure)))
