(((name . "u8vector?") (signature lambda (obj) boolean?) (tags pure predicate))
 ((name . "make-u8vector")
  (signature lambda ((integer? size) (integer? size)) u8vector?)
  (tags pure))
 ((name . "u8vector")
  (signature lambda ((integer? value) ...) u8vector?)
  (tags pure))
 ((name . "u8vector->list")
  (signature lambda ((u8vector? vec)) list?)
  (tags pure))
 ((name . "list->u8vector")
  (signature lambda ((list? proper-list)) u8vector?)
  (tags pure))
 ((name . "u8vector-length")
  (signature lambda ((u8vector? vec)) integer?)
  (tags pure))
 ((name . "u8vector-ref")
  (signature lambda ((u8vector? vec) (integer? i)) integer?)
  (tags pure))
 ((name . "u8vector-set!")
  (signature lambda ((u8vector? vec) (integer? i) (integer? value)) undefined))
 ((name . "u8vector=?")
  (signature lambda ((u8vector? vec1) (u8vector? vec2)) boolean?)
  (tags pure))
 ((name . "u8vector-compare")
  (signature lambda ((u8vector? vec1) (u8vector? vec2)) integer?)
  (tags pure))
 ((name . "u8vector-copy!")
  (signature
   lambda
   ((u8vector? source)
    (integer? source-start)
    (u8vector? target)
    (integer? target-start)
    (integer? n))
   undefined))
 ((name . "u8vector-copy")
  (signature lambda ((u8vector? vec)) u8vector?)
  (tags pure)))
