(((name . "f32vector?")
  (signature lambda (obj) boolean?)
  (tags pure predicate))
 ((name . "make-f32vector")
  (signature
   case-lambda
   (((integer? size)) f32vector?)
   (((integer? size) (real? fill)) f32vector?))
  (tags pure))
 ((name . "f32vector-length")
  (signature lambda ((f32vector? vec)) integer?)
  (tags pure))
 ((name . "f32vector-ref")
  (signature lambda ((f32vector? vec) (integer? i)) real?)
  (tags pure))
 ((name . "f32vector-set!")
  (signature lambda ((f32vector? vec) (integer? i) (real? value)) undefined))
 ((name . "f32vector->list")
  (signature lambda ((f32vector? vec)) list?)
  (tags pure))
 ((name . "list->f32vector")
  (signature lambda ((list? proper-list)) f32vector?)
  (tags pure)))
