;; maps library -> scheme implementation to be tested with
(

 (r5rs . bigloo)
 ;; r6rs
 ((rnrs base (6)) . chez)
 ((rnrs arithmetic bitwise (6)) . chez)
 ((rnrs arithmetic fixnums (6)) . chez)
 ((rnrs arithmetic flonums (6)) . chez)
 ((rnrs bytevectors (6)) . chez)
 ((rnrs conditions (6)) . chez)
 ((rnrs control (6)) . chez)
 ((rnrs enums (6)) . chez)
 ((rnrs eval (6)) . chez)
 ((rnrs exceptions (6)) . chez)
 ((rnrs files (6)) . chez)
 ((rnrs files (6)) . chez)
 ((rnrs hashtables (6)) . chez)
 ((rnrs io ports (6)) . chez)
 ((rnrs io simple (6)) . chez)
 ((rnrs lists (6)) . chez)
 ((rnrs mutable-pairs (6)) . chez)
 ((rnrs mutable-strings (6)) . chez)
 ((rnrs programs (6)) . chez)
 ((rnrs r5rs (6)) . chez)
 ((rnrs records inspection (6)) . chez)
 ((rnrs records procedural (6)) . chez)
 ((rnrs records syntactic (6)) . chez)
 ((rnrs sorting (6)) . chez)
 ((rnrs unicode (6)) . chez)

 ;; r7rs small
 ((scheme base) . chibi)
 ((scheme case-lambda) . chibi)
 ((scheme complex) . chibi)
 ((scheme char) . chibi)
 ((scheme cxr) . chibi)
 ((scheme eval) . chibi)
 ((scheme file) . chibi)
 ((scheme inexact) . chibi)
 ((scheme lazy) . chibi)
 ((scheme load) . chibi)
 ((scheme process-context) . chibi)
 ((scheme read) . chibi)
 ((scheme repl) . chibi)
 ((scheme time) . chibi)
 ((scheme write) . chibi)
 ((scheme r5rs) . chibi)
 
 ; r7rs large red
 ((scheme box) . chibi)
 ((scheme comparator) . chibi)
 ((scheme charset) . chibi)
 ((scheme ephemeron) . gauche)
 ((scheme generator) . gauche)
 ((scheme hash-table) . chibi)
 ((scheme ideque) . chibi)
 ((scheme ilist) . chibi)
 ((scheme list) . gauche)
 ((scheme list-queue) . chibi)
 ((scheme lseq) . chibi)
 ((scheme rlist) . chibi)
 ((scheme set) . chibi)
 ((scheme stream) . chibi)
 ((scheme sort) . chibi)
 ((scheme text) . chibi)
 ((scheme vector) . chibi)
 
 ; r7rs large tangerine
 ((scheme bitwise) . chibi)
 ((scheme bytevector) . gauche)
 ((scheme division) . gauche)
 ((scheme fixnum) . gauche)
 ((scheme flonum) . gauche)
 ((scheme mapping) . gauche)
 ((scheme hashmap) . gauche)
 ((scheme regex) . chibi)
 ((scheme show) . gauche)
 ((scheme vector base) . gauche)
 ((scheme vector u8) . gauche)
 ((scheme vector s8) . gauche)
 ((scheme vector u16) . gauche)
 ((scheme vector s16) . gauche)
 ((scheme vector u32) . gauche)
 ((scheme vector s32) . gauche)
 ((scheme vector u64) . gauche)
 ((scheme vector s64) . gauche)
 ((scheme vector f32) . gauche)
 ((scheme vector f64) . gauche)
 ((scheme vector c64) . gauche)
 ((scheme vector c128) . gauche)

 ((srfi 0) . chibi)
 ((srfi 1) . gauche)
 ((srfi 2) . chibi)
 ((srfi 4) . gauche)
 ((srfi 5) . chibi)
 ((srfi 6) . chibi)
 ((srfi 8) . chibi)
 ((srfi 9) . chibi)
 ((srfi 11) . chibi)
 ((srfi 13) . gauche)
 ((srfi 14) . chibi)
 ((srfi 16) . chibi)
 ((srfi 17) . gauche)
 ((srfi 18) . chibi)
 ((srfi 19) . gauche)
 ((srfi 21) . gambit)
 ((srfi 23) . chibi)
 ((srfi 25) . gauche)
 ((srfi 26) . chibi)
 ((srfi 27) . chibi)
 ((srfi 28) . gauche)
 ((srfi 29) . gauche)
 ((srfi 31) . chibi)
 ((srfi 34) . gauche)
 ((srfi 35) . gauche)
 ((srfi 36) . gauche)
 ((srfi 37) . gauche)
 ((srfi 38) . chibi)
 ((srfi 39) . chibi)
 ((srfi 41) . chibi)
 ((srfi 42) . guile)
 ((srfi 43) . gauche)
 ((srfi 45) . gauche)
 ((srfi 46) . gauche)
 ((srfi 47) . ignore)
 ((srfi 48) . ignore)
 ((srfi 54) . ignore)
 ((srfi 59) . ignore)
 ((srfi 60) . gauche)
 ((srfi 61) . chibi)
 ((srfi 63) . ignore)
 ((srfi 64) . gauche)
 ((srfi 66) . gauche)
 ((srfi 67) . guile)
 ((srfi 69) . chibi)
 ((srfi 71) . guile)
 ((srfi 74) . gauche)
 ((srfi 78) . gauche)
 ((srfi 87) . chibi)
 ((srfi 88) . guile)
 ((srfi 95) . chibi)
 ((srfi 98) . gauche)
 ((srfi 99) . chibi)
 ((srfi 99) . chibi)
 ((srfi 99) . chibi)
 ((srfi 99 records procedural) . chibi)
 ((srfi 99 records inspection) . chibi)
 ((srfi 99 records syntactic) . chibi)
 ((srfi 101) . chibi)
 ((srfi 111) . chibi)
 ((srfi 112) . gauche)
 ((srfi 113) . chibi)
 ((srfi 115) . chibi)
 ((srfi 116) . chibi)
 ((srfi 117) . chibi)
 ((srfi 124) . gauche)
 ((srfi 125) . chibi)
 ((srfi 127) . chibi)
 ((srfi 128) . chibi)
 ((srfi 129) . chibi)
 ((srfi 130) . chibi)
 ((srfi 131) . gauche)
 ((srfi 131 records procedural) . gauche)
 ((srfi 131 records inspection) . gauche)
 ((srfi 131 records syntactic) . gauche)
 ((srfi 132) . chibi)
 ((srfi 133) . chibi)
 ((srfi 134) . chibi)
 ((srfi 135) . chibi)
 ((srfi 141) . chibi)
 ((srfi 143) . gauche)
 ((srfi 144) . gauche)
 ((srfi 145) . chibi)
 ((srfi 146) . gauche)
 ((srfi 146 hash) . gauche)
 ((srfi 151) . chibi)
 ((srfi 152) . gauche)
 ((srfi 154) . gauche)
 ((srfi 156) . chibi)
 ((srfi 158) . chibi)
 ((srfi 159) . gauche)
 ((srfi 160 base) . gauche)
 ((srfi 160 u8) . gauche)
 ((srfi 160 s8) . gauche)
 ((srfi 160 u16) . gauche)
 ((srfi 160 s16) . gauche)
 ((srfi 160 u32) . gauche)
 ((srfi 160 s32) . gauche)
 ((srfi 160 u64) . gauche)
 ((srfi 160 s64) . gauche)
 ((srfi 160 f32) . gauche)
 ((srfi 160 f64) . gauche)
 ((srfi 160 c64) . gauche)
 ((srfi 160 c128) . gauche)
 ((srfi 193) . chibi)
 ((srfi 219) . chibi)

 (bigloo . ignore)

)
