(
  ((name . "Linux")
   (url . "/downloads/scmindex-linuxstatic-x64.zip")
   (checksum . "SHA 256: @linux-checksum@"))
  ((name . "Macos (ARM)")
   (url . "/downloads/scmindex-macos-arm.zip")
   (checksum . "SHA 256: @macos-arm-checksum@"))
  ((name . "Macos (x64)")
   (url . "/downloads/scmindex-macos-x64.zip")
   (checksum . "SHA 256: @macos-x64-checksum@"))
  ((name . "Windows")
   (url . "/downloads/scmindex-win-x64.zip")
   (checksum . "SHA 256: @win-checksum@"))
)
