(
  ((name . "Linux")
   (url . "/downloads/scmindex-linuxstatic-x64.zip")
   (checksum . "@linux-checksum@"))
  ((name . "Macos (ARM)")
   (url . "/downloads/scmindex-macos-arm.zip")
   (checksum . "@macos-arm-checksum@"))
  ((name . "Macos (x64)")
   (url . "/downloads/scmindex-macos-x64.zip")
   (checksum . "@macos-x64-checksum@"))
  ((name . "Windows")
   (url . "/downloads/scmindex-win-x64.zip")
   (checksum . "@win-checksum@"))
)
