(
 ;; r6rs
 ((rnrs base (6)) . #t)
 ((rnrs arithmetic bitwise (6)) . #t)
 ((rnrs arithmetic fixnum (6)) . #t)
 ((rnrs arithmetic flonum (6)) . #t)
 ((scheme bytevector) . (rnrs bytevectors (6)))
 ((rnrs conditions (6)) . #t)
 ((rnrs control (6)) . #t)
 ((scheme eval) . (rnrs eval (6)))
 ((rnrs files (6)) . #t)
 ((rnrs hashtables (6)) . #t)
 ((rnrs io ports (6)) . #t)
 ((rnrs io simple (6)) . #t)
 ((rnrs enums (6)) . #t)
 ((rnrs exceptions (6)) . #t)
 ((rnrs lists (6)) . #t)
 ((rnrs mutable-pairs (6)) . #t)
 ((rnrs mutable-strings (6)) . #t)
 ((rnrs programs (6)) . #t)
 ((rnrs r5rs (6)) . #t)
 ((rnrs records inspection (6)) . #t)
 ((rnrs records procedural (6)) . #t)
 ((rnrs records syntactic (6)) . #t)
 ((rnrs sorting (6)) . #t)
 ((rnrs unicode (6)) . #t)

 ;; misc srfi, added in order of popularity according to https://misc.lassi.io/2019/srfi-implementation-counts.scm
 ((scheme list) . (srfi 1))
 ((srfi 8) . #t)
 ((srfi 2) . #t)
 ((srfi 9) . #t)
 ((srfi 6) . #t)
 ((srfi 0) . #t)
 ((scheme charset) . (srfi 14))
 ((srfi 23) . #t)
 ((srfi 27) . #t)
 ((srfi 39) . #t)
 ((srfi 13) . #t)
 ((srfi 26) . #t)
 ((srfi 60) . #t)
 ((scheme case-lambda) . (srfi 16))
 ((srfi 28) . #t)
 ((srfi 11) . #t)
 ((srfi 19) . #t)
 ((srfi 38) . #t)
 ((srfi 31) . #t)
 ((srfi 42) . #t)
 ((srfi 69) . #t)
 ((srfi 17) . #t)
 ((srfi 37) . #t)
 ((scheme stream) . (srfi 41))
 ((scheme vector) . (srfi 43))
 ((srfi 37) . #t)
 ((srfi 45) . #t)
 ((srfi 61) . #t)
 ((srfi 25) . #t)
 ((srfi 34) . #t)
 ((srfi 78) . #t)
 ((srfi 48) . #t)
 ((srfi 64) . #t)
 ((srfi 67) . #t)
 ((scheme comparator) . (srfi 128))
 ((srfi 35) . #t)

)
