(
 ;; r6rs
 ((rnrs base (6)) . #t)
 ((rnrs arithmetic bitwise (6)) . #t)
 ((rnrs arithmetic fixnum (6)) . #t)
 ((rnrs arithmetic flonum (6)) . #t)
 ((scheme bytevector) . (rnrs bytevectors (6)))
 ((rnrs conditions (6)) . #t)
 ((rnrs control (6)) . #t)
 ((scheme eval) . (rnrs eval (6)))
 ((rnrs files (6)) . #t)
 ((rnrs hashtables (6)) . #t)
 ((rnrs io ports (6)) . #t)
 ((rnrs io simple (6)) . #t)
 ((rnrs enums (6)) . #t)
 ((rnrs exceptions (6)) . #t)
 ((rnrs lists (6)) . #t)
 ((rnrs mutable-pairs (6)) . #t)
 ((rnrs mutable-strings (6)) . #t)
 ((rnrs programs (6)) . #t)
 ((rnrs r5rs (6)) . #t)
 ((rnrs records inspection (6)) . #t)
 ((rnrs records procedural (6)) . #t)
 ((rnrs records syntactic (6)) . #t)
 ((rnrs sorting (6)) . #t)
 ((rnrs unicode (6)) . #t)

 ;; r7rs small
 ((scheme base) . #t)
 ((scheme case-lambda) . #t)
 ((scheme complex) . #t)
 ((scheme char) . #t)
 ((scheme cxr) . #t)
 ((scheme eval) . #t)
 ((scheme file) . #t)
 ((scheme inexact) . #t)
 ((scheme lazy) . #t)
 ((scheme load) . #t)
 ((scheme process-context) . #t)
 ((scheme r5rs) . #t)
 ((scheme read) . #t)
 ((scheme repl) . #t)
 ((scheme time) . #t)
 ((scheme write) . #t)

 ; r7rs large red
 ((scheme box) . (srfi srfi-111))
 ((scheme charset) . (srfi srfi-14))
 ((scheme list) . (srfi srfi-1))
 ((scheme stream) . (srfi srfi-41))

 ((srfi 8) . (srfi srfi-8))
 ((srfi 2) . (srfi srfi-2))
 ((srfi 27) . (srfi srfi-27))
 ((srfi 13) . (srfi srfi-13))
 ((srfi 26) . (srfi srfi-26))
 ((srfi 60) . (srfi srfi-60))
 ((srfi 28) . (srfi srfi-28))
 ((srfi 19) . (srfi srfi-19))
 ((srfi 38) . (srfi srfi-38))
 ((srfi 31) . (srfi srfi-31))
 ((srfi 42) . (srfi srfi-42))
 ((srfi 69) . (srfi srfi-69))
 ((srfi 17) . (srfi srfi-17))
 ((srfi 37) . (srfi srfi-37))
 ((srfi 45) . (srfi srfi-45))
 ((srfi 61) . (srfi srfi-61))
 ((srfi 18) . (srfi srfi-18))
 ((srfi 64) . (srfi srfi-64))
 ((srfi 67) . (srfi srfi-67))
 ((srfi 35) . (srfi srfi-35))

 )
