(
 ("R6RS" . "filters/r6rs.scm")
 ("R7RS small" . "filters/r7rs-small.scm")
 ("R7RS large" . "filters/r7rs-large.scm")
 ("R7RS large + SRFIs" . "filters/portable.scm")
 ("Chibi" . "filters/chibi.scm")
 ("Kawa" . "filters/kawa.scm")
 ("Chicken" . "filters/chicken.scm")
 ("Gauche" . "filters/gauche.scm")
 ("Gambit" . "filters/gambit.scm")
 ("Guile" . "filters/guile.scm")
 ("MIT" . "filters/mit.scm")
)
