(
 ;; r7rs small
 ((scheme base) . #t)
 ((scheme case-lambda) . #t)
 ((scheme complex) . #t)
 ((scheme char) . #t)
 ((scheme cxr) . #t)
 ((scheme eval) . #t)
 ((scheme file) . #t)
 ((scheme inexact) . #t)
 ((scheme lazy) . #t)
 ((scheme load) . #t)
 ((scheme process-context) . #t)
 ((scheme r5rs) . #t)
 ((scheme read) . #t)
 ((scheme repl) . #t)
 ((scheme time) . #t)
 ((scheme write) . #t)
 
 ((srfi 0) . #t)
 ((srfi 1) . #t)
 ((srfi 2) . #t)
 ((srfi 4) . #t)
 ((srfi 6) . #t)
 ((srfi 8) . #t)
 ((srfi 9) . #t)
 ((srfi 11) . #t)
 ((srfi 13) . #t)
 ((srfi 14) . #t)
 ((srfi 16) . #t)
 ((srfi 17) . #t)
 ((srfi 23) . #t)
 ((srfi 25) . #t)
 ((srfi 26) . #t)
 ((srfi 28) . #t)
 ((srfi 35) . #t)
 ((srfi 37) . #t)
 ((srfi 38) . #t)
 ((srfi 39) . #t)
 ((srfi 41) . #t)
 ((srfi 45) . #t)
 ((srfi 60) . #t)
 ((srfi 64) . #t)
 ((srfi 66) . #t)
 ((srfi 67) . #t)
 ((srfi 69) . #t)
 ((srfi 95) . #t)
 ((srfi 101) . #t)

)
