(
 ;; r7rs small
 ((scheme base) . #t)
 ((scheme case-lambda) . #t)
 ((scheme complex) . #t)
 ((scheme char) . #t)
 ((scheme cxr) . #t)
 ((scheme eval) . #t)
 ((scheme file) . #t)
 ((scheme inexact) . #t)
 ((scheme lazy) . #t)
 ((scheme load) . #t)
 ((scheme process-context) . #t)
 ((scheme r5rs) . #t)
 ((scheme read) . #t)
 ((scheme repl) . #t)
 ((scheme time) . #t)
 ((scheme write) . #t)
 
 ((srfi 0) . #t)
 ((srfi 1) . #t)
 ((srfi 2) . #t)
 ((srfi 6) . #t)
 ((srfi 8) . #t)
 ((srfi 9) . #t)
 ((srfi 14) . #t)
 ((srfi 23) . #t)
 ((srfi 27) . #t)
 ((srfi 31) . #t)
 ((srfi 39) . #t)
 ((srfi 69) . #t)
 ((srfi 115) . #t)
 ((srfi 124) . #t)
 ((srfi 125) . #t)
 ((srfi 128) . #t)
 ((srfi 133) . #t)
 ((srfi 143) . #t)
 ((srfi 158) . #t)
 )
