(
 ;; r7rs small
 ((scheme base) . #t)
 ((scheme case-lambda) . #t)
 ((scheme complex) . #t)
 ((scheme char) . #t)
 ((scheme cxr) . #t)
 ((scheme eval) . #t)
 ((scheme file) . #t)
 ((scheme inexact) . #t)
 ((scheme lazy) . #t)
 ((scheme load) . #t)
 ((scheme process-context) . #t)
 ((scheme r5rs) . #t)
 ((scheme read) . #t)
 ((scheme repl) . #t)
 ((scheme time) . #t)
 ((scheme write) . #t)
 
 ; r7rs large red
 ((scheme box) . #t) 
 ((scheme comparator) . #t)
 ((scheme charset) . #t)
 ((scheme ephemeron) . #t)
 ((scheme generator) . #t)
 ((scheme hash-table) . #t)
 ((scheme ideque) . #t)
 ((scheme ilist) . #t)
 ((scheme list) . #t)
 ((scheme list-queue) . #t)
 ((scheme lseq) . #t)
 ((scheme rlist) . #t)
 ((scheme set) . #t)
 ((scheme stream) . #t)
 ((scheme sort) . #t)
 ((scheme text) . #t)
 ((scheme vector) . #t)
 
 ; r7rs large tangerine
 ((scheme bitwise) . #t)
 ((scheme bytevector) . #t)
 ((scheme division) . #t)
 ((scheme fixnum) . #t)
 ((scheme flonum) . #t)
 ((scheme mapping) . #t)
 ((scheme mapping hash) . #t)
 ((scheme regex) . #t)
 ((scheme show) . #t)
 ((scheme vector base) . #t)
 ((scheme vector u8) . #t)
 ((scheme vector s8) . #t)
 ((scheme vector u16) . #t)
 ((scheme vector s16) . #t)
 ((scheme vector u32) . #t)
 ((scheme vector s32) . #t)
 ((scheme vector u64) . #t)
 ((scheme vector s64) . #t)
 ((scheme vector f32) . #t)
 ((scheme vector f64) . #t)
 ((scheme vector c64) . #t)
 ((scheme vector c128) . #t)

 ((srfi 0) . #t)
 ((srfi 1) . #t)
 ((srfi 2) . #t)
 ((srfi 4) . #t)
 ((srfi 5) . #t)
 ((srfi 6) . #t)
 ((srfi 8) . #t)
 ((srfi 9) . #t)
 ((srfi 11) . #t)
 ((srfi 13) . #t)
 ((srfi 14) . #t)
 ((srfi 16) . #t)
 ((srfi 17) . #t)
 ((srfi 18) . #t)
 ((srfi 19) . #t)
 ((srfi 21) . #t)
 ((srfi 23) . #t)
 ((srfi 25) . #t)
 ((srfi 26) . #t)
 ((srfi 27) . #t)
 ((srfi 28) . #t)
 ((srfi 29) . #t)
 ((srfi 31) . #t)
 ((srfi 34) . #t)
 ((srfi 35) . #t)
 ((srfi 36) . #t)
 ((srfi 37) . #t)
 ((srfi 38) . #t)
 ((srfi 39) . #t)
 ((srfi 41) . #t)
 ((srfi 42) . #t)
 ((srfi 43) . #t)
 ((srfi 45) . #t)
 ((srfi 46) . #t)
 ((srfi 48) . #t)
 ((srfi 59) . #t)
 ((srfi 60) . #t)
 ((srfi 61) . #t)
 ((srfi 64) . #t)
 ((srfi 66) . #t)
 ((srfi 67) . #t)
 ((srfi 69) . #t)
 ((srfi 71) . #t)
 ((srfi 78) . #t)
 ((srfi 87) . #t)
 ((srfi 88) . #t)
 ((srfi 95) . #t)
 ((srfi 101) . #t)
 ((srfi 111) . #t)
 ((srfi 113) . #t)
 ((srfi 115) . #t)
 ((srfi 116) . #t)
 ((srfi 117) . #t)
 ((srfi 124) . #t)
 ((srfi 125) . #t)
 ((srfi 127) . #t)
 ((srfi 128) . #t)
 ((srfi 132) . #t)
 ((srfi 133) . #t)
 ((srfi 134) . #t)
 ((srfi 135) . #t)
 ((srfi 141) . #t)
 ((srfi 143) . #t)
 ((srfi 144) . #t)
 ((srfi 145) . #t)
 ((srfi 146) . #t)
 ((srfi 146 hash) . #t)
 ((srfi 151) . #t)
 ((srfi 158) . #t)
 ((srfi 159) . #t)
 ((srfi 160 base) . #t)
 ((srfi 160 u8) . #t)
 ((srfi 160 s8) . #t)
 ((srfi 160 u16) . #t)
 ((srfi 160 s16) . #t)
 ((srfi 160 u32) . #t)
 ((srfi 160 s32) . #t)
 ((srfi 160 u64) . #t)
 ((srfi 160 s64) . #t)
 ((srfi 160 f32) . #t)
 ((srfi 160 f64) . #t)
 ((srfi 160 c64) . #t)
 ((srfi 160 c128) . #t)
)
