(
 ;; r7rs small
 ((scheme base) . #t)
 ((scheme case-lambda) . #t)
 ((scheme complex) . #t)
 ((scheme char) . #t)
 ((scheme cxr) . #t)
 ((scheme eval) . #t)
 ((scheme file) . #t)
 ((scheme inexact) . #t)
 ((scheme lazy) . #t)
 ((scheme load) . #t)
 ((scheme process-context) . #t)
 ((scheme read) . #t)
 ((scheme repl) . #t)
 ((scheme time) . #t)
 ((scheme write) . #t)
 
 ; r7rs large red
 ((scheme box) . #t)
 ((scheme comparator) . #t)
 ((scheme charset) . #t)
 ((scheme ephemeron) . #t)
 ((scheme generator) . #t)
 ((scheme hash-table) . #t)
 ((scheme ideque) . #t)
 ((scheme ilist) . #t)
 ((scheme list) . #t)
 ((scheme list-queue) . #t)
 ((scheme lseq) . #t)
 ((scheme rlist) . #t)
 ((scheme set) . #t)
 ((scheme stream) . #t)
 ((scheme sort) . #t)
 ((scheme text) . #t)
 ((scheme vector) . #t)
 
 ; r7rs large tangerine
 ((scheme bitwise) . #t)
 ((scheme bytevector) . #t)
 ((scheme division) . #t)
 ((scheme fixnum) . #t)
 ((scheme flonum) . #t)
 ((scheme mapping) . #t)
 ((scheme mapping hash) . #t)
 ((scheme regex) . #t)
 ((scheme show) . #t)
 ((scheme vector base) . #t)
 ((scheme vector u8) . #t)
 ((scheme vector s8) . #t)
 ((scheme vector u16) . #t)
 ((scheme vector s16) . #t)
 ((scheme vector u32) . #t)
 ((scheme vector s32) . #t)
 ((scheme vector u64) . #t)
 ((scheme vector s64) . #t)
 ((scheme vector f32) . #t)
 ((scheme vector f64) . #t)
 ((scheme vector c64) . #t)
 ((scheme vector c128) . #t)

)
