(
 ;; r6rs
 ((rnrs base (6)) . #t)
 ((rnrs arithmetic bitwise (6)) . #t)
 ((rnrs arithmetic fixnum (6)) . #t)
 ((rnrs arithmetic flonum (6)) . #t)
 ((rnrs bytevectors (6)) . #t)
 ((rnrs conditions (6)) . #t)
 ((rnrs control (6)) . #t)
 ((rnrs eval (6)) . #t)
 ((rnrs files (6)) . #t)
 ((rnrs hashtables (6)) . #t)
 ((rnrs io ports (6)) . #t)
 ((rnrs io simple (6)) . #t)
 ((rnrs enums (6)) . #t)
 ((rnrs exceptions (6)) . #t)
 ((rnrs lists (6)) . #t)
 ((rnrs mutable-pairs (6)) . #t)
 ((rnrs mutable-strings (6)) . #t)
 ((rnrs programs (6)) . #t)
 ((rnrs r5rs (6)) . #t)
 ((rnrs records inspection (6)) . #t)
 ((rnrs records procedural (6)) . #t)
 ((rnrs records syntactic (6)) . #t)
 ((rnrs sorting (6)) . #t)
 ((rnrs unicode (6)) . #t)

 ((srfi 1) . #t)
 ((srfi 2) . #t)
 ((srfi 4) . #t)
 ((srfi 5) . #t)
 ((srfi 6) . #t)
 ((srfi 8) . #t)
 ((srfi 9) . #t)
 ((srfi 11) . #t)
 ((srfi 13) . #t)
 ((srfi 14) . #t)
 ((srfi 16) . #t)
 ((srfi 17) . #t)
 ((srfi 18) . #t)
 ((srfi 19) . #t)
 ((srfi 23) . #t)
 ((srfi 25) . #t)
 ((srfi 26) . #t)
 ((srfi 27) . #t)
 ((srfi 28) . #t)
 ((srfi 29) . #t)
 ((srfi 31) . #t)
 ((srfi 34) . #t)
 ((srfi 35) . #t)
 ((srfi 38) . #t)
 ((srfi 39) . #t)
 ((srfi 41) . #t)
 ((srfi 42) . #t)
 ((srfi 43) . #t)
 ((srfi 45) . #t)
 ((srfi 48) . #t)
 ((srfi 54) . #t)
 ((srfi 59) . #t)
 ((srfi 60) . #t)
 ((srfi 61) . #t)
 ((srfi 64) . #t)
 ((srfi 66) . #t)
 ((srfi 67) . #t)
 ((srfi 69) . #t)
 ((srfi 71) . #t)
 ((srfi 74) . #t)
 ((srfi 78) . #t)
 ((srfi 87) . #t)
 ((srfi 98) . #t)
)
