(
 (r5rs . scheme)
 ((srfi 1) . #t)
 ((srfi 2) . #t)
 ((srfi 4) . #t)
 ((srfi 5) . #t)
 ((srfi 6) . #t)
 ((srfi 8) . #t)
 ((srfi 9) . #t)
 ((srfi 11) . #t)
 ((srfi 13) . #t)
 ((srfi 14) . #t)
 ((srfi 16) . #t)
 ((srfi 17) . #t)
 ((srfi 19) . #t)
 ((srfi 23) . #t)
 ((srfi 25) . #t)
 ((srfi 26) . #t)
 ((srfi 27) . #t)
 ((srfi 28) . #t)
 ((srfi 31) . #t)
 ((srfi 34) . #t)
 ((srfi 37) . #t)
 ((srfi 39) . #t)
 ((srfi 42) . #t)
 ((srfi 43) . #t)
 ((srfi 45) . #t)
 ((srfi 60) . #t)
 ((srfi 61) . #t)
 ((srfi 66) . #t)
 ((srfi 67) . #t)
 ((srfi 71) . #t)
 ((srfi 74) . #t)
 ((srfi 78) . #t)
 ((srfi 95) . #t)
)
