(
 ;; r7rs small
 ((scheme base) . #t)
 ((scheme case-lambda) . #t)
 ((scheme complex) . #t)
 ((scheme char) . #t)
 ((scheme cxr) . #t)
 ((scheme eval) . #t)
 ((scheme file) . #t)
 ((scheme inexact) . #t)
 ((scheme lazy) . #t)
 ((scheme load) . #t)
 ((scheme process-context) . #t)
 ((scheme r5rs) . #t)
 ((scheme read) . #t)
 ((scheme repl) . #t)
 ((scheme time) . #t)
 ((scheme write) . #t)

 ((srfi 0) . #t)
 ((srfi 1) . #t)
 ((srfi 2) . #t)
 ((srfi 8) . #t)
 ((srfi 27) . #t)
 ((srfi 28) . #t)
 ((srfi 37) . #t)
 ((srfi 64) . #t)
 ((srfi 111) . #t)
 ((srfi 125) . #t)
 ((srfi 128) . #t)
 ((srfi 158) . #t)
)
