name: 'Render and deploy docs'
on:
  push:
    branches:
      - main
      - remove-site-part

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    container:
      image: asciidoctor/docker-asciidoctor:1.106
    steps:
      - uses: actions/checkout@v4
      - name: 'Build README.adoc'
        run: 'asciidoctor README.adoc -o index.html'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'index.html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
