name: Lint angular app
on:
  push:
    paths:
      - '.github/workflows/lint.yml'
      - 'scheme-index-app/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: |
          cd scheme-index-app
          npm install
          npm run lint
