name: 'Test data format on pull request'
on:
  pull_request:

jobs:
  validatedata:
    runs-on: ubuntu-latest
    container:
      image: schemers/chicken:5
    steps:
      - name: 'Validate data'
        run: 'cd scheme-index-util; bash validatedata-native.sh'
